
(()=>{'use strict';
const $=id=>document.getElementById(id);
let rows=[],currentEmail='',token=sessionStorage.getItem('univers_token')||sessionStorage.getItem('nyxia_univers_token')||'';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{try{return new Date(d).toLocaleString('fr-CA',{dateStyle:'medium',timeStyle:'short'})}catch(_){return d||''}};
async function api(path,method='GET',body){const o={method,headers:{'Content-Type':'application/json','X-Univers-Token':token}};if(body)o.body=JSON.stringify(body);const r=await fetch(path,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Erreur');return d}
function grouped(){const m={};for(const x of rows){const e=(x.from||x.clientEmail||'').toLowerCase();if(!e)continue;(m[e]||(m[e]=[])).push(x)}
return Object.entries(m).map(([email,msgs])=>{msgs.sort((a,b)=>new Date(a.date||0)-new Date(b.date||0));const last=msgs[msgs.length-1]||{};return{email,msgs,last,portal:last.portal||msgs.find(x=>x.portal)?.portal||'Portail',name:last.fromName||msgs.find(x=>x.fromName)?.fromName||email,unread:msgs.filter(x=>!x.isAdmin&&!x.read).length}}).sort((a,b)=>new Date(b.last.date||0)-new Date(a.last.date||0))}
function renderInbox(){const q=$('searchInbox').value.toLowerCase(),pf=$('portalFilter').value,sf=$('statusFilter').value;const gs=grouped().filter(g=>(!q||(g.email+' '+g.name).toLowerCase().includes(q))&&(!pf||g.portal===pf)&&(!sf||(sf==='unread'?g.unread>0:g.unread===0)));
$('inboxList').innerHTML=gs.length?gs.map(g=>`<div class="conv ${g.email===currentEmail?'active':''}" data-email="${esc(g.email)}"><div class="conv-name">${esc(g.name)}</div>${g.unread?`<span class="unread">${g.unread} nouveau${g.unread>1?'x':''}</span>`:''}<span class="conv-portal">${esc(g.portal)}</span><div class="conv-preview">${esc(g.last.message||g.last.reply||'')}</div></div>`).join(''):'<div class="empty">Aucun message.</div>';document.querySelectorAll('[data-email]').forEach(x=>x.onclick=()=>openThread(x.dataset.email))}
function refreshPortals(){const vals=[...new Set(rows.map(x=>x.portal).filter(Boolean))].sort(),cur=$('portalFilter').value;$('portalFilter').innerHTML='<option value="">Tous les portails</option>'+vals.map(x=>`<option ${x===cur?'selected':''}>${esc(x)}</option>`).join('')}
function openThread(email){currentEmail=email;const g=grouped().find(x=>x.email===email);if(!g)return;$('threadHead').innerHTML=`<strong>${esc(g.name)}</strong><span>${esc(g.email)} · ${esc(g.portal)}</span>`;const html=[];
for(const m of g.msgs){if(m.isAdmin)html.push(`<div class="mrow admin"><div class="mbubble"><div class="who">${esc(m.fromName||'Diane Boyer')}</div>${esc(m.message||'')}<span class="meta">${fmt(m.date)}</span></div></div>`);else{html.push(`<div class="mrow client"><div class="mbubble">${esc(m.message||'')}<span class="meta">${fmt(m.date)} · ${esc(m.portal||g.portal)}</span></div></div>`);if(m.reply)html.push(`<div class="mrow admin"><div class="mbubble"><div class="who">${esc(m.replyFrom||'Diane Boyer')}</div>${esc(m.reply)}<span class="meta">${fmt(m.replyDate)}</span></div></div>`)}}
$('threadMessages').innerHTML=html.join('')||'<div class="empty large">Aucun message.</div>';$('threadMessages').scrollTop=$('threadMessages').scrollHeight;$('replyText').disabled=false;$('sendReply').disabled=false;renderInbox()}
async function load(){try{const d=await api('/api/messaging/admin/messages');rows=d.messages||[];refreshPortals();renderInbox();if(currentEmail)openThread(currentEmail)}catch(e){$('inboxList').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function reply(){const text=$('replyText').value.trim();if(!currentEmail||!text)return;const g=grouped().find(x=>x.email===currentEmail);if(!g)return;const target=[...g.msgs].reverse().find(x=>!x.isAdmin)||g.last;$('sendReply').disabled=true;$('replyStatus').textContent='Envoi…';try{await api('/api/messaging/admin/reply','POST',{clientEmail:currentEmail,msgId:target.id,reply:text,replyFrom:$('replyAs').value,portal:g.portal});$('replyText').value='';$('replyStatus').textContent='✓ Réponse envoyée.';await load()}catch(e){$('replyStatus').textContent=e.message}finally{$('sendReply').disabled=false}}
$('refreshInbox').onclick=load;$('sendReply').onclick=reply;['searchInbox','portalFilter','statusFilter'].forEach(id=>$(id).addEventListener(id==='searchInbox'?'input':'change',renderInbox));load();
})();
