name = "univers"
main = "_worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "CASHFLOW_KV"
id = "106db6da016d49d2b480452f19bad695"

[[d1_databases]]
binding = "DB"
database_name = "nyxia-cercles-db"
database_id = "a21fd813-06fa-41f1-b744-07bf1c5c7951"

[vars]
SITE_URL = "https://univers.nyxia.top"
