name = "univers"
main = "_worker.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "CASHFLOW_KV"
id = "106db6da016d49d2b480452f19bad695"

[[kv_namespaces]]
binding = "SPIRITUEL_KV"
id = "3e730b1c49f94e32a97cceff3b60a773"

[[d1_databases]]
binding = "DB"
database_name = "nyxia-cercles-db"
database_id = "a21fd813-06fa-41f1-b744-07bf1c5c7951"

[vars]
SITE_URL = "https://univers.nyxia.top"
SYSTEME_ACTIVATION_FIELD = "lien_activation_nyxia"
SYSTEME_ACTIVATION_TAG_ID = "2221814"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "univers-livres"

[ai]
binding = "AI"

