
(()=>{'use strict';const $=id=>document.getElementById(id),API='/api/superadmin4/projects';let chars=[],current='',tools=[];
const slug=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(u,o={}){const r=await fetch(u,{credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'HTTP '+r.status);return d}
async function loadChars(){const d=await api('/api/superadmin4/characters');chars=d.characters||[];renderChars()}
function renderChars(){const box=$('characters');box.innerHTML='';for(const c of chars){const d=document.createElement('div');d.className='char';d.innerHTML='<input type="checkbox" id="c-'+c.code+'">'+(c.image?'<img src="'+esc(c.image)+'">':'<div>✦</div>')+'<div><b>'+esc(c.name||c.code)+'</b><div class="muted">'+esc(c.sub||c.visibleRole||'Personnage NyXia')+'</div></div><select id="p-'+c.code+'"><option value="principal">Mes Conversations</option><option value="atelier">Atelier</option><option value="hidden">Masqué</option></select>';box.appendChild(d)}}
function selected(){return chars.filter(c=>$('c-'+c.code)?.checked).map(c=>({...c,key:c.code,placement:$('p-'+c.code).value}))}
function draft(){return{title:$('title').value,short:$('short').value,portalId:slug($('portalId').value||$('short').value||$('title').value),workerName:slug($('workerName').value||$('short').value||$('title').value),host:$('host').value.trim().toLowerCase(),mission:$('mission').value,agents:selected(),tools}}
function apply(p={}){for(const k of ['title','short','portalId','workerName','host','mission'])$(k).value=p[k]||'';for(const c of chars){const a=(p.agents||[]).find(x=>(x.key||x.code)===c.code);$('c-'+c.code).checked=!!a;if(a)$('p-'+c.code).value=a.placement||'principal'}tools=p.tools||[];renderTools()}
async function loadProjects(){const d=await api(API),s=$('projectSelect');s.innerHTML='<option value="">— Nouveau portail —</option>';for(const p of d.projects||[]){const o=document.createElement('option');o.value=p.id;o.textContent=p.title;s.appendChild(o)}}
async function save(){const b={title:$('title').value||'Nouveau portail',data:draft()};const d=current?await api(API+'/'+current,{method:'PUT',body:JSON.stringify(b)}):await api(API,{method:'POST',body:JSON.stringify(b)});current=d.project.id;await loadProjects();$('projectSelect').value=current;return d.project}
async function openProject(){const id=$('projectSelect').value;if(!id)return;const d=await api(API+'/'+id);current=id;apply(d.project.data||{})}
function renderTools(){const b=$('tools');b.innerHTML='';tools.forEach((t,i)=>{const d=document.createElement('div');d.className='tool';d.innerHTML='<input value="'+esc(t.name||'')+'" placeholder="Nom"><input value="'+esc(t.path||'/outil.html')+'" placeholder="/outil.html"><button>Retirer</button><input type="file" accept=".html,text/html" style="grid-column:1/-1">';const ins=d.querySelectorAll('input');ins[0].oninput=e=>t.name=e.target.value;ins[1].oninput=e=>t.path=e.target.value;ins[2].onchange=async e=>{const f=e.target.files[0];if(f)t.content=await f.text()};d.querySelector('button').onclick=()=>{tools.splice(i,1);renderTools()};b.appendChild(d)})}
function b64(s){const u=new TextEncoder().encode(s);let b='';u.forEach(x=>b+=String.fromCharCode(x));return btoa(b)}
function card(a){return '<article class="panel card agent-card" data-agent-card="'+esc(a.key)+'">'+(a.image?'<img class="avatar" src="'+esc(a.image)+'">':'<div class="brand-orb">✦</div>')+'<div><h3>'+esc(a.name)+'</h3><p>'+esc(a.sub||a.visibleRole||'')+'</p></div></article>'}
async function compile(){const st=$('status');try{st.textContent='Sauvegarde…';const pr=await save(),p=pr.data;if(!p.title||!p.host||!p.portalId)throw Error('Nom, ID et sous-domaine requis.');if(!/^[a-z0-9.-]+\.nyxia\.top$/.test(p.host))throw Error('Sous-domaine nyxia.top invalide.');if(!(p.agents||[]).length)throw Error('Choisis au moins un personnage.');
 st.textContent='Lecture et vérification de la coque…';const r=await fetch('/superadmin4/portail-shell-template.zip',{cache:'no-store'});if(!r.ok)throw Error('Coque introuvable.');const z=await JSZip.loadAsync(await r.arrayBuffer());
 const required=['_worker.js','index.html','login.html','dashbord.html','messagerie.html','banque-medias.html','chat-base.html','wrangler.toml','css/nyxia-core.css','js/portal-chat.js','js/portal-dashboard.js'];for(const f of required)if(!z.file(f))throw Error('Coque incomplète : '+f+' absent.');
 let w=await z.file('_worker.js').async('string');for(const marker of ['PORTAL_CONFIG_B64','/api/image/generate','/api/messagerie/send','/api/formation/list','DG_GRANT_PREFIX'])if(!w.includes(marker))throw Error('Worker incomplet : '+marker+' absent.');
 let chat=await z.file('js/portal-chat.js').async('string');for(const marker of ['🔊 Écouter','📋 Copier','↺ Réessayer','⬇ PDF','/api/image/generate'])if(!chat.includes(marker))throw Error('Chat incomplet : '+marker+' absent.');
 const cfg={id:p.portalId,title:p.title,shortTitle:p.short||p.title,mission:p.mission,activeAgents:p.agents.filter(a=>a.placement!=='hidden').map(a=>a.key),agents:p.agents};
 w=w.replace("__PORTAL_CONFIG_B64__",b64(JSON.stringify(cfg)));z.file('_worker.js',w);
 let wr=await z.file('wrangler.toml').async('string');wr=wr.replaceAll('__WORKER_NAME__',p.workerName).replaceAll('__HOST__',p.host).replaceAll('__PORTAL_ID__',p.portalId);z.file('wrangler.toml',wr);
 const visible=p.agents.filter(a=>a.placement!=='hidden'),principals=visible.filter(a=>a.placement==='principal'),atelier=visible.filter(a=>a.placement==='atelier'),pages={messagerie:'/messagerie.html',media:'/banque-medias.html'};
 const cards=principals.map(card).join(''),nav=principals.map(a=>'<div class="nav-item" data-page="'+esc(a.key)+'"><span class="nav-icon">✦</span>'+esc(a.name)+'</div>').join(''),anav=atelier.map(a=>'<div class="nav-item" data-page="'+esc(a.key)+'"><span class="nav-icon">✨</span>'+esc(a.name)+'</div>').join('');
 for(const a of visible){pages[a.key]='/chat-'+a.key+'.html';let h=await z.file('chat-base.html').async('string');h=h.replaceAll('__AGENT_NAME__',esc(a.name)).replaceAll('__AGENT_SUB__',esc(a.sub||a.visibleRole||'')).replaceAll('__AGENT_AVATAR_HTML__',a.image?'<img class="avatar" src="'+esc(a.image)+'">':'<div class="brand-orb">✦</div>').replaceAll('__AGENT_JSON__',JSON.stringify(a)).replaceAll('__PORTAL_TITLE_JSON__',JSON.stringify(p.title)).replaceAll('__PORTAL_SHORT_TITLE__',esc(p.short||p.title));z.file('chat-'+a.key+'.html',h)}
 z.remove('chat-base.html');
 for(const f of ['index.html','dashbord.html']){let h=await z.file(f).async('string');h=h.replaceAll('__PORTAL_TITLE__',esc(p.title)).replaceAll('__PORTAL_SHORT_TITLE__',esc(p.short||p.title)).replaceAll('__PORTAL_MISSION__',esc(p.mission||''));if(f==='index.html')h=h.replaceAll('__LANDING_AGENT_CARDS__',visible.map(card).join(''));else h=h.replaceAll('__PORTAL_AGENT_NAV__',nav).replaceAll('__PORTAL_ATELIER_NAV__',anav).replaceAll('__PORTAL_AGENT_CARDS__',cards).replaceAll('__PORTAL_PAGES_JSON__',JSON.stringify(pages)).replaceAll('__PORTAL_SPECIAL_TOOLS__',(p.tools||[]).map(t=>'<div class="nav-item" data-page="tool-'+t.id+'"><span class="nav-icon">🧰</span>'+esc(t.name||'Outil')+'</div>').join(''));z.file(f,h)}
 let log=await z.file('login.html').async('string');log=log.replaceAll('__PORTAL_SHORT_TITLE__',esc(p.short||p.title));z.file('login.html',log);
 for(const t of p.tools||[]){t.id=t.id||crypto.randomUUID().slice(0,8);if(t.content){const path=(t.path||'/outil.html').replace(/^\//,'');z.file(path,t.content);pages['tool-'+t.id]='/'+path}}
 // dashboard pages JSON after tools
 let d=await z.file('dashbord.html').async('string');d=d.replace(JSON.stringify({messagerie:'/messagerie.html',media:'/banque-medias.html',...Object.fromEntries(visible.map(a=>[a.key,'/chat-'+a.key+'.html']))}),JSON.stringify(pages));z.file('dashbord.html',d);
 z.file('portal-manifest.json',JSON.stringify({...cfg,host:p.host,workerName:p.workerName,features:['grand-hall','chat','formation-vivante','messagerie','media-bank','image-generation','degustation'],compiledAt:new Date().toISOString()},null,2));
 st.textContent='Enregistrement du portail pour Dégustations…';await api('/api/superadmin4/register-portal',{method:'POST',body:JSON.stringify({id:p.portalId,name:p.title})});
 st.textContent='Compression…';const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Portail-'+slug(p.short||p.title)+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),20000);st.textContent='ZIP complet prêt ✓ · portail enregistré pour Dégustations.'}catch(e){st.textContent='⚠ '+e.message}}
$('openBtn').onclick=openProject;$('newBtn').onclick=()=>{current='';apply({});$('projectSelect').value=''};$('saveBtn').onclick=save;$('compileBtn').onclick=compile;$('reloadChars').onclick=loadChars;$('addTool').onclick=()=>{tools.push({id:crypto.randomUUID().slice(0,8),name:'',path:'/outil.html',content:''});renderTools()};document.addEventListener('DOMContentLoaded',async()=>{await loadChars();await loadProjects()})})();
