// NyXia — Super Admin 4 V2 · compilateur de portails
const PROJECT_INDEX_KEY='superadmin4:projects:index',PROJECT_PREFIX='superadmin4:project:',COOKIE_NAME='nyxia_univers',PROFILE_PREFIX='nyxia:personnage-profil:';
function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),sid=v=>clean(v,120).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'');
function token(req){const h=req.headers.get('X-Univers-Token');if(h)return h.trim();const m=(req.headers.get('Cookie')||'').match(/(?:^|;\s*)nyxia_univers=([^;]+)/);return m?m[1]:''}
async function admin(req,env){const t=token(req);if(!t)return false;const r=await env.CASHFLOW_KV.get('univers:session:'+t);if(!r)return false;try{const s=JSON.parse(r);return !s.role||s.role==='superadmin'}catch(_){return true}}
async function index(env){try{return JSON.parse(await env.CASHFLOW_KV.get(PROJECT_INDEX_KEY)||'[]')}catch(_){return[]}}
async function saveIndex(env,a){await env.CASHFLOW_KV.put(PROJECT_INDEX_KEY,JSON.stringify(a.slice(0,500)))}
async function readProject(env,id){const r=await env.CASHFLOW_KV.get(PROJECT_PREFIX+id);return r?JSON.parse(r):null}
async function writeProject(env,p){await env.CASHFLOW_KV.put(PROJECT_PREFIX+p.id,JSON.stringify(p));let a=(await index(env)).filter(x=>x.id!==p.id);a.unshift({id:p.id,title:p.title,updatedAt:p.updatedAt});await saveIndex(env,a);return p}
async function projects(req,env,u){const parts=u.pathname.split('/').filter(Boolean),id=sid(parts[3]||'');if(req.method==='GET'&&!id)return json({projects:await index(env)});if(req.method==='POST'&&!id){const b=await req.json().catch(()=>({})),now=new Date().toISOString(),p={id:crypto.randomUUID(),title:b.title||'Nouveau portail',data:b.data||{},createdAt:now,updatedAt:now};return json({project:await writeProject(env,p)},201)}if(id&&req.method==='GET'){const p=await readProject(env,id);return p?json({project:p}):json({error:'Projet introuvable.'},404)}if(id&&req.method==='PUT'){const old=await readProject(env,id);if(!old)return json({error:'Projet introuvable.'},404);const b=await req.json().catch(()=>({})),p={...old,title:b.title||old.title,data:b.data||old.data,updatedAt:new Date().toISOString()};return json({project:await writeProject(env,p)})}return json({error:'Route projet inconnue.'},404)}
async function profiles(env){let cur,out=[];do{const l=await env.CASHFLOW_KV.list({prefix:PROFILE_PREFIX,cursor:cur});for(const k of l.keys||[]){try{const p=JSON.parse(await env.CASHFLOW_KV.get(k.name)||'{}');if(p.code)out.push(p)}catch(_){}}cur=l.list_complete?null:l.cursor}while(cur);return out}
async function characters(env){let base=[];try{const raw=await env.CASHFLOW_KV.get('nyxia:personnages')||await env.CASHFLOW_KV.get('formations:agents');base=JSON.parse(raw||'[]')}catch(_){}
 const pf=await profiles(env),map=new Map();for(const x of base){const code=sid(x.code||x.id||x.nom||x.name);if(code)map.set(code,{code,name:x.nom||x.name||code,sub:x.sub||'',image:x.image||'',portail:x.portail||''})}for(const p of pf){const code=sid(p.code||p.name);if(!code)continue;const b=map.get(code)||{code};map.set(code,{...b,...p,code,name:p.name||b.name||code,sub:p.sub||p.visibleRole||b.sub||'',image:p.image||b.image||'',greeting:p.greeting||p.welcomeMessage||'',mission:p.mission||p.prompt||'',personality:p.personality||'',tone:p.tone||p.languageStyle||'',voiceId:p.voiceId||'',modelPrimary:p.modelPrimary||'',modelFallback:p.modelFallback||'',vectorNamespace:p.vectorNamespace||code})}
 return[...map.values()].filter(x=>x.active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name),'fr'))}
async function registerPortal(env,b){const id=sid(b.id),name=clean(b.name,160);if(!id||!name)throw Error('ID et nom requis.');let list=[];try{list=JSON.parse(await env.CASHFLOW_KV.get('univers:portals')||'[]')}catch(_){}const i=list.findIndex(x=>x.id===id),row={id,name,active:true};if(i>=0)list[i]={...list[i],...row};else list.push(row);await env.CASHFLOW_KV.put('univers:portals',JSON.stringify(list));return row}
export default{async fetch(req,env){if(!(await admin(req,env)))return json({error:'Non autorisé.'},401);const u=new URL(req.url);try{
 if(req.method==='GET'&&u.pathname==='/superadmin4/portail-shell-template.zip'){const r=await env.ASSETS.fetch(new Request(new URL('/superadmin4/portail-shell-template.zip',req.url),req));return new Response(r.body,{status:r.status,headers:{'Content-Type':'application/zip','Cache-Control':'private, no-store'}})}
 if(u.pathname.startsWith('/api/superadmin4/projects'))return projects(req,env,u);
 if(u.pathname==='/api/superadmin4/characters'&&req.method==='GET')return json({characters:await characters(env)});
 if(u.pathname==='/api/superadmin4/register-portal'&&req.method==='POST')return json({ok:true,portal:await registerPortal(env,await req.json())});
 if(u.pathname==='/api/superadmin4/health')return json({ok:true,version:'v2-simple-complete'});
 return json({error:'Route inconnue.'},404)}catch(e){return json({error:String(e?.message||e)},500)}}}
