// NyXia Univers — Super Admin 4 · Portails
const PROJECT_INDEX_KEY='superadmin4:projects:index',PROJECT_PREFIX='superadmin4:project:',TOOL_PREFIX='superadmin4:project-tool:',PROFILE_PREFIX='nyxia:personnage-profil:',COOKIE_NAME='nyxia_univers';
function json(d,s=200){return new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n);const sid=v=>clean(v,120).replace(/[^a-zA-Z0-9_-]/g,'');
function tok(req){const h=req.headers.get('X-Univers-Token');if(h)return h.trim();const m=(req.headers.get('Cookie')||'').match(/(?:^|;\s*)nyxia_univers=([^;]+)/);return m?m[1]:''}
async function admin(req,env){const t=tok(req);if(!t||!env.CASHFLOW_KV)return false;const r=await env.CASHFLOW_KV.get('univers:session:'+t);if(!r)return false;try{const s=JSON.parse(r);return !s.role||s.role==='superadmin'}catch(_){return true}}
async function idx(env){try{return JSON.parse(await env.CASHFLOW_KV.get(PROJECT_INDEX_KEY)||'[]')}catch(_){return[]}}async function saveIdx(env,a){await env.CASHFLOW_KV.put(PROJECT_INDEX_KEY,JSON.stringify(a.sort((x,y)=>String(y.updatedAt||'').localeCompare(String(x.updatedAt||''))).slice(0,500)))}
const tk=(p,t)=>TOOL_PREFIX+p+':'+t;
async function read(env,id){const r=await env.CASHFLOW_KV.get(PROJECT_PREFIX+id);if(!r)return null;const p=JSON.parse(r);p.data=p.data||{};for(const t of p.data.tools||[])if(t.id&&t.hasContent)t.content=await env.CASHFLOW_KV.get(tk(id,t.id))||'';return p}
async function write(env,p){p.data=p.data||{};const core=structuredClone(p),tools=[];for(const x of p.data.tools||[]){const id=sid(x.id||crypto.randomUUID().replace(/-/g,'').slice(0,16));if(typeof x.content==='string')await env.CASHFLOW_KV.put(tk(p.id,id),x.content);tools.push({...x,id,content:undefined,hasContent:typeof x.content==='string'||x.hasContent})}core.data.tools=tools;await env.CASHFLOW_KV.put(PROJECT_PREFIX+p.id,JSON.stringify(core));let a=(await idx(env)).filter(x=>x.id!==p.id);a.push({id:p.id,title:p.title||p.data.title||'Portail',updatedAt:p.updatedAt,createdAt:p.createdAt,toolCount:tools.length});await saveIdx(env,a);return read(env,p.id)}
async function projects(req,env,u){const a=u.pathname.split('/').filter(Boolean),id=sid(a[3]||''),act=a[4]||'';if(req.method==='GET'&&!id)return json({projects:await idx(env)});if(req.method==='POST'&&!id){const b=await req.json().catch(()=>({})),now=new Date().toISOString(),p={...b,id:sid(b.id||crypto.randomUUID()),kind:'nyxia-portal',title:b.title||b.data?.title||'Nouveau portail',status:'brouillon',createdAt:now,updatedAt:now,data:b.data||{}};return json({ok:true,project:await write(env,p)},201)}if(id&&req.method==='GET'&&!act){const p=await read(env,id);return p?json({project:p}):json({error:'Projet introuvable.'},404)}if(id&&req.method==='PUT'&&!act){const old=await read(env,id);if(!old)return json({error:'Projet introuvable.'},404);const b=await req.json().catch(()=>({})),p={...old,...b,id,updatedAt:new Date().toISOString(),data:b.data||old.data};return json({ok:true,project:await write(env,p)})}if(id&&req.method==='DELETE'){await env.CASHFLOW_KV.delete(PROJECT_PREFIX+id);await saveIdx(env,(await idx(env)).filter(x=>x.id!==id));return json({ok:true})}if(id&&act==='duplicate'&&req.method==='POST'){const p=await read(env,id);if(!p)return json({error:'Projet introuvable.'},404);p.id=crypto.randomUUID();p.title+=' — copie';p.createdAt=p.updatedAt=new Date().toISOString();return json({ok:true,project:await write(env,p)},201)}return json({error:'Route projet inconnue.'},404)}
async function profiles(req,env,u){const code=sid(u.searchParams.get('code')||'').toLowerCase();if(req.method==='GET'){if(code){const r=await env.CASHFLOW_KV.get(PROFILE_PREFIX+code);return json({profile:r?JSON.parse(r):null})}let cur,out=[];do{const l=await env.CASHFLOW_KV.list({prefix:PROFILE_PREFIX,cursor:cur});for(const k of l.keys||[]){try{out.push(JSON.parse(await env.CASHFLOW_KV.get(k.name)))}catch(_){}}cur=l.list_complete?null:l.cursor}while(cur);return json({profiles:out})}if(req.method==='POST'){const b=await req.json().catch(()=>({})),c=sid(b.code||b.name||'').toLowerCase();if(!c)return json({error:'Code requis.'},400);const p={code:c,name:clean(b.name,120)||c,sub:clean(b.sub,180),prompt:clean(b.prompt,12000),personality:clean(b.personality,8000),image:clean(b.image,2000),welcomeVideo:clean(b.welcomeVideo,2000),voiceId:clean(b.voiceId,180),portail:clean(b.portail,80).toLowerCase(),updatedAt:new Date().toISOString()};await env.CASHFLOW_KV.put(PROFILE_PREFIX+c,JSON.stringify(p));return json({ok:true,profile:p})}if(req.method==='DELETE'&&code){await env.CASHFLOW_KV.delete(PROFILE_PREFIX+code);return json({ok:true})}return json({error:'Méthode inconnue.'},405)}
export default{async fetch(request,env){if(!(await admin(request,env)))return json({error:'Non autorisé.'},401);const u=new URL(request.url);try{if(request.method==='GET'&&u.pathname==='/superadmin4/portail-shell-template.zip'){const r=await env.ASSETS.fetch(new Request(new URL('/superadmin4/portail-shell-template.zip',request.url),request));if(!r.ok)return json({error:'Coque Portail locale absente.'},502);return new Response(r.body,{headers:{'Content-Type':'application/zip','Cache-Control':'private, no-store'}})}if(u.pathname.startsWith('/api/superadmin4/projects'))return projects(request,env,u);if(u.pathname==='/api/superadmin4/personnages/profile')return profiles(request,env,u);if(u.pathname==='/api/superadmin4/health')return json({ok:true,kv:!!env.CASHFLOW_KV,version:'17.0-coque-propre'});return json({error:'Route Super Admin 4 inconnue.'},404)}catch(e){return json({error:String(e?.message||e)},500)}}};