(()=>{'use strict';const A=window.NYXIA_AGENT||{};const $=id=>document.getElementById(id);let token=new URLSearchParams(location.search).get('t')||sessionStorage.getItem('nyxia_token')||'';if(token)sessionStorage.setItem('nyxia_token',token);let userName=localStorage.getItem('nyxia_username')||'toi';let history=[];let attachment=null;let recognition=null;let listening=false;let lastUserText='';const storeKey='nyxia_chat_'+(A.key||'agent');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function avatar(size='msg-avatar'){if(A.image)return `<img class="${size}" src="${esc(A.image)}" alt="${esc(A.name||'Personnage')}" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'msg-fallback',textContent:${JSON.stringify('✦')}}))">`;return `<span class="msg-fallback">${esc(A.icon||'✦')}</span>`}
function loadHistory(){try{history=JSON.parse(sessionStorage.getItem(storeKey)||'[]');if(!Array.isArray(history))history=[]}catch(_){history=[]}}
function saveHistory(){try{sessionStorage.setItem(storeKey,JSON.stringify(history.slice(-50)))}catch(_){}}
function basicMarkdown(s){let t=esc(s);t=t.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');const lines=t.split(/\n/);let out='',inList=false;for(const line of lines){if(/^\s*[-•]\s+/.test(line)){if(!inList){out+='<ul>';inList=true}out+='<li>'+line.replace(/^\s*[-•]\s+/,'')+'</li>'}else{if(inList){out+='</ul>';inList=false}if(line.trim())out+='<p>'+line+'</p>';else out+='<br>'}}if(inList)out+='</ul>';return out}
function driveId(u){const m=String(u).match(/drive\.google\.com\/(?:file\/d\/|open\?id=|uc\?(?:export=[^&]+&)?id=)([A-Za-z0-9_-]+)/);return m?m[1]:null}
function youtubeId(u){const m=String(u).match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?m[1]:null}
function mediaNode(kind,url,label){url=String(url||'').trim();if(!/^https:\/\//i.test(url))return null;const card=document.createElement('div');card.className='media-card';const gd=driveId(url),yt=youtubeId(url);if(kind==='VIDEO'){if(yt){const f=document.createElement('iframe');f.className='video-frame';f.src='https://www.youtube.com/embed/'+yt;f.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';f.allowFullscreen=true;card.appendChild(f)}else if(gd){const f=document.createElement('iframe');f.className='video-frame';f.src='https://drive.google.com/file/d/'+gd+'/preview';f.allow='autoplay';card.appendChild(f)}else{const v=document.createElement('video');v.src=url;v.controls=true;v.playsInline=true;v.preload='metadata';card.appendChild(v)}}else if(kind==='AUDIO'){if(gd){const f=document.createElement('iframe');f.className='drive-audio';f.src='https://drive.google.com/file/d/'+gd+'/preview';f.allow='autoplay';card.appendChild(f)}else{const a=document.createElement('audio');a.src=url;a.controls=true;a.preload='metadata';card.appendChild(a)}}else if(kind==='IMAGE'){if(gd){const f=document.createElement('iframe');f.className='drive-doc';f.src='https://drive.google.com/file/d/'+gd+'/preview';card.appendChild(f)}else{const im=document.createElement('img');im.src=url;im.alt=label||'Image';card.appendChild(im)}}else if(kind==='PDF'){if(gd){const f=document.createElement('iframe');f.className='drive-doc';f.src='https://drive.google.com/file/d/'+gd+'/preview';card.appendChild(f)}const a=document.createElement('a');a.className='file-link';a.href=url;a.target='_blank';a.rel='noopener';a.textContent='📄 '+(label||'Ouvrir le PDF');card.appendChild(a)}else if(kind==='LINK'){const a=document.createElement('a');a.className='file-link';a.href=url;a.target='_blank';a.rel='noopener';a.textContent='🔗 '+(label||'Ouvrir la ressource');card.appendChild(a)}return card}
function splitMedia(raw){const media=[];let text=String(raw||'');const add=(kind,val)=>{let url=val,label='';const pipe=val.indexOf('|');if(pipe>-1){url=val.slice(0,pipe).trim();label=val.slice(pipe+1).trim()}const n=mediaNode(kind,url,label);if(n)media.push(n);return ''};for(const k of ['VIDEO','AUDIO','IMAGE','PDF','LINK']){const re=new RegExp('\\['+k+'\\s*:\\s*([^\\]\\r\\n]+)\\]','gi');text=text.replace(re,(_,v)=>add(k,v))}return{text:text.replace(/\n{3,}/g,'\n\n').trim(),media}}
function actions(host,text){const bar=document.createElement('div');bar.className='message-actions';const mk=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',fn);bar.appendChild(b);return b};mk('🔊 Écouter',e=>speak(e.currentTarget,text));mk('📋 Copier',e=>navigator.clipboard.writeText(stripMarkers(text)).then(()=>{const b=e.currentTarget;b.textContent='✓ Copié';setTimeout(()=>b.textContent='📋 Copier',1400)}));mk('↺ Réessayer',()=>retry());mk('⬇ PDF',()=>printPdf(text));host.appendChild(bar)}
function stripMarkers(s){return String(s||'').replace(/\[(VIDEO|AUDIO|IMAGE|PDF|LINK)\s*:[^\]]+\]/gi,'').trim()}
function addMessage(role,text,saveIt=true){const row=document.createElement('div');row.className='msg '+role;if(role==='bot')row.insertAdjacentHTML('beforeend',avatar());const wrap=document.createElement('div');wrap.className='bubble-wrap';const bubble=document.createElement('div');bubble.className='msg-bubble';const parsed=splitMedia(text);bubble.innerHTML=basicMarkdown(parsed.text);for(const n of parsed.media)bubble.appendChild(n);wrap.appendChild(bubble);if(role==='bot')actions(wrap,text);row.appendChild(wrap);$('messages').appendChild(row);$('messages').scrollTop=$('messages').scrollHeight;if(saveIt){history.push({role:role==='bot'?'assistant':'user',content:String(text||'')});history=history.slice(-50);saveHistory()}}
function renderHistory(){const copy=history.slice();history=[];for(const m of copy)addMessage(m.role==='assistant'?'bot':'user',m.content,true)}
function typing(on){let e=$('typing-row');if(on&&!e){e=document.createElement('div');e.id='typing-row';e.className='msg bot typing';e.innerHTML=avatar()+'<div class="bubble-wrap"><div class="msg-bubble"><span class="nx-dots"><i></i><i></i><i></i></span></div></div>';$('messages').appendChild(e);$('messages').scrollTop=$('messages').scrollHeight}else if(!on&&e)e.remove()}
async function auth(){if(!token){location.replace('/login');return false}try{const r=await fetch('/api/check-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!d.valid){location.replace('/login');return false}userName=d.firstname||userName;return true}catch(_){return true}}
async function send(textOverride=null,fromRetry=false){const input=$('message-input');const text=textOverride!==null?String(textOverride):input.value.trim();if(!text&&!attachment)return;lastUserText=text;if(textOverride===null){input.value='';input.style.height='auto'}const shown=text+(attachment?'\n📎 '+attachment.name:'');if(!fromRetry)addMessage('user',shown);typing(true);$('send-btn').disabled=true;const att=attachment;attachment=null;$('attachment-state').hidden=true;try{const body={message:text,history:history.slice(-14,-1),userName,agent:A.key,token,attachment:att};const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));typing(false);if(!r.ok)throw Error(d.error||'Réponse indisponible.');addMessage('bot',d.content||'Petite interruption… réessaie dans un instant 💜')}catch(err){typing(false);addMessage('bot','⚠ '+(err.message||'Petite interruption… réessaie.'))}finally{$('send-btn').disabled=false}}
function retry(){const users=history.filter(x=>x.role==='user');const last=users[users.length-1];if(!last)return;while(history.length&&history[history.length-1].role==='assistant')history.pop();saveHistory();send(last.content,true)}
function printPdf(text){const clean=stripMarkers(text);const w=window.open('','_blank','noopener,noreferrer');if(!w)return;w.document.write('<!doctype html><meta charset="utf-8"><title>'+esc(A.name||'NyXia')+'</title><style>body{font:16px Arial,sans-serif;max-width:760px;margin:50px auto;line-height:1.6;color:#111}h1{font-size:22px}pre{white-space:pre-wrap;font:inherit}</style><h1>'+esc(A.name||'NyXia')+'</h1><pre>'+esc(clean)+'</pre><script>onload=()=>setTimeout(()=>print(),100)<\/script>');w.document.close()}
function browserSpeak(text){if(!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(stripMarkers(text));u.lang='fr-CA';speechSynthesis.cancel();speechSynthesis.speak(u)}
async function speak(btn,text){if(btn._audio){btn._audio.pause();btn._audio=null;btn.textContent='🔊 Écouter';return}btn.textContent='⏹';try{const r=await fetch('/api/tts/nyxia',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,text:stripMarkers(text),agent:A.key})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.proxyUrl)throw Error(d.error||'Voix non configurée');const a=new Audio(d.proxyUrl);btn._audio=a;a.onended=a.onerror=()=>{btn._audio=null;btn.textContent='🔊 Écouter'};await a.play()}catch(_){btn.textContent='🔊 Écouter';browserSpeak(text)}}
async function formationState(){try{const r=await fetch('/api/formation/list?agent='+encodeURIComponent(A.key)+'&token='+encodeURIComponent(token));const d=await r.json();if(r.ok&&Array.isArray(d.formations)&&d.formations.length){const w=$('formation-launch-wrap'),b=$('formation-btn');if(w)w.hidden=false;b.textContent=d.hasProgress?'▶ Continuer ma formation':'🎓 Formation Vivante';b.dataset.mode=d.hasProgress?'continue':'start'}}catch(_){}}
function newChat(){if(!confirm('Effacer cette conversation avec '+(A.name||'ce personnage')+' ?'))return;history=[];saveHistory();$('messages').innerHTML='';welcome()}
function welcome(){if(history.length)return renderHistory();addMessage('bot',A.greeting||'Je suis là. Dis-moi ce que tu veux faire avancer dans ce portail.',false)}
function toggleMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('La reconnaissance vocale est disponible surtout dans Chrome ou Edge.');if(listening){try{recognition.stop()}catch(_){}return}recognition=new SR();recognition.lang='fr-CA';recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('mic-btn').textContent='⏹'};recognition.onend=()=>{listening=false;$('mic-btn').textContent='🎤'};recognition.onerror=recognition.onend;recognition.onresult=e=>{$('message-input').value=e.results[0][0].transcript;send()};recognition.start()}
async function readImage(file){if(!file.type.startsWith('image/'))throw Error('Pour l’instant, la pièce jointe du chat accepte les images.');if(file.size>6*1024*1024)throw Error('Image trop lourde (maximum 6 Mo).');const dataUrl=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)});return{name:file.name,type:file.type,dataUrl}}
document.addEventListener('DOMContentLoaded',async()=>{const ok=await auth();if(!ok)return;document.querySelectorAll('[data-suggestion]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.suggestion||b.textContent.trim())));const av=$('agent-avatar');if(A.image){av.className='';av.innerHTML='<img src="'+esc(A.image)+'" alt="'+esc(A.name||'')+'">'}else{av.className='chat-header-badge';av.textContent=A.icon||'✦'};loadHistory();welcome();formationState();$('send-btn').addEventListener('click',()=>send());$('new-chat-btn').addEventListener('click',newChat);$('formation-btn').addEventListener('click',()=>send($('formation-btn').dataset.mode==='continue'?'continue ma formation':'commence ma formation'));$('mic-btn').addEventListener('click',toggleMic);$('message-input').addEventListener('input',function(){this.style.height='auto';this.style.height=Math.min(this.scrollHeight,130)+'px'});$('message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('file-input').addEventListener('change',async function(){const f=this.files&&this.files[0];if(!f)return;try{attachment=await readImage(f);$('attachment-state').hidden=false;$('attachment-state').textContent='📎 '+f.name+' · joint au prochain message'}catch(err){alert(err.message)}this.value=''})})})();
