(()=>{'use strict';
const $=id=>document.getElementById(id);const qsa=s=>[...document.querySelectorAll(s)];
let catalog=[],profiles={},current='',form={},history=[],formations=[],portals=[],brain=null,activeFormation=null,tab='identite';
const MEDIA=['VIDEO','AUDIO','IMAGE','PDF','LINK','CANVA','IMAGE_GENERATE'];
const TOOLS=['formation-vivante','vector-brain','image-generation','web-links','pdf','audio','video','canva'];
const TABS=[['identite','Identité'],['mission','Mission & prompt'],['personnalite','Personnalité'],['expertise','Expertise & limites'],['presence','Accueil & présence'],['voix','Voix & médias'],['formation','Formation Vivante'],['cerveau','Cerveau'],['portails','Portails & outils'],['notes','Notes & versions']];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)}
async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(r.status===401){location.href='/';throw Error('Session expirée.')}if(!r.ok)throw Error(d.error||d.message||('Erreur '+r.status));return d}
function blank(){return{schemaVersion:3,code:'',name:'',visibleRole:'',shortDescription:'',biography:'',mission:'',systemPrompt:'',personality:'',values:'',tone:'',languageStyle:'',favoriteExpressions:'',avoidExpressions:'',expertise:'',skills:'',methods:'',teachingStyle:'',ethics:'',limits:'',canDo:'',cannotDo:'',welcomeMessage:'',suggestions:[],image:'',welcomeVideo:'',voiceName:'',voiceId:'',voiceNotes:'',primaryPortal:'',portalAssignments:[],formationRefs:[],vectorNamespace:'',resources:[],allowedMedia:[...MEDIA],tools:[...TOOLS],internalNotes:'',tags:[],active:true}}
function normalize(p={}){const b=blank();return{...b,...p,code:slug(p.code||p.id||p.name),name:p.name||p.nom||'',visibleRole:p.visibleRole||p.sub||'',mission:p.mission||p.prompt||'',systemPrompt:p.systemPrompt||'',welcomeMessage:p.welcomeMessage||p.greeting||'',primaryPortal:p.primaryPortal||p.portail||'',suggestions:Array.isArray(p.suggestions)?p.suggestions:[],tags:Array.isArray(p.tags)?p.tags:[],resources:Array.isArray(p.resources)?p.resources:[],allowedMedia:Array.isArray(p.allowedMedia)&&p.allowedMedia.length?p.allowedMedia:[...MEDIA],tools:Array.isArray(p.tools)?p.tools:[...TOOLS],portalAssignments:Array.isArray(p.portalAssignments)?p.portalAssignments:[]}}
function status(t,k=''){const e=$('status');e.textContent=t;e.className='status '+k}
async function auth(){try{const d=await api('/api/check-auth',{method:'POST',body:'{}'});if(!d.valid){location.href='/';return false}return true}catch(_){location.href='/';return false}}
async function loadAll(){status('Chargement…');const [c,pj]=await Promise.all([api('/api/personnages'),api('/api/superadmin4/projects').catch(()=>({projects:[]}))]);catalog=c.personnages||c.agents||[];portals=pj.projects||[];const pf=await api('/api/superadmin4/personnages/profile').catch(()=>({profiles:[]}));profiles=Object.fromEntries((pf.profiles||[]).map(x=>[x.code,x]));renderCharacterList();fillSelect();status('Prêt.','ok')}
function renderCharacterList(){const host=$('characterList');if(!host)return;const search=($('search')?.value||'').toLowerCase().trim();const rows=catalog.map(c=>{const p=normalize(profiles[c.code]||{code:c.code,name:c.nom,primaryPortal:c.portail});return{...c,p}}).filter(x=>!search||(`${x.nom} ${x.code} ${x.p.visibleRole} ${(x.p.tags||[]).join(' ')}`).toLowerCase().includes(search));host.innerHTML=rows.length?rows.map(x=>`<div class="character-card ${current===x.code?'active':''}" data-code="${esc(x.code)}">${x.p.image?`<img src="${esc(x.p.image)}" alt="">`:`<span style="width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#0f1c3f">✦</span>`}<div><strong>${esc(x.nom)}</strong><div class="hint">${esc(x.p.visibleRole||x.code)}</div></div></div>`).join(''):'<div class="empty">Aucun personnage.</div>';qsa('[data-code]').forEach(x=>x.onclick=()=>openCharacter(x.dataset.code))}
function fillSelect(){const s=$('characterSelect');if(!s)return;s.innerHTML='<option value="">— Choisir un personnage —</option>'+catalog.map(c=>`<option value="${esc(c.code)}">${esc(c.nom)}${c.portail?' · '+esc(c.portail):''}</option>`).join('');if(current)s.value=current}
async function openCharacter(code){collect();current=slug(code);const base=catalog.find(x=>x.code===current)||{};const d=await api('/api/superadmin4/personnages/profile?code='+encodeURIComponent(current)).catch(()=>({profile:null}));form=normalize(d.profile||profiles[current]||{code:current,name:base.nom,primaryPortal:base.portail});profiles[current]=form;await refreshRelated();renderAll();status('Fiche chargée.','ok')}
async function refreshRelated(){if(!current){history=[];formations=[];brain=null;return}const [h,f,b]=await Promise.all([api('/api/superadmin4/personnages/history?code='+encodeURIComponent(current)).catch(()=>({history:[]})),api('/api/superadmin4/personnages/formations?code='+encodeURIComponent(current)).catch(()=>({formations:[]})),api('/api/vectorize/stats?agent='+encodeURIComponent(current)).catch(()=>({data:{}}))]);history=h.history||[];formations=f.formations||[];brain=b.data||b.brain||{};}
function newCharacter(){collect();current='';form=blank();history=[];formations=[];brain=null;activeFormation=null;fillSelect();renderCharacterList();renderAll();status('Nouvelle fiche.')}
function tabs(){const h=$('tabs');h.innerHTML=TABS.map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${l}</button>`).join('');qsa('[data-tab]').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;tabs();renderPanel()})}
function inp(k,label,type='input',hint=''){const v=form[k]??'';return `<div class="${type==='textarea'?'full large':''}"><label>${esc(label)}</label>${type==='textarea'?`<textarea id="f-${k}">${esc(v)}</textarea>`:`<input id="f-${k}" value="${esc(v)}">`}${hint?`<div class="hint">${esc(hint)}</div>`:''}</div>`}
function collect(){qsa('[id^="f-"]').forEach(el=>form[el.id.slice(2)]=el.value);if($('suggestions'))form.suggestions=$('suggestions').value.split('\n').map(x=>x.trim()).filter(Boolean);if($('tags'))form.tags=$('tags').value.split(',').map(x=>x.trim()).filter(Boolean);if($('primaryPortal'))form.primaryPortal=$('primaryPortal').value.trim();if($('vectorNamespace'))form.vectorNamespace=$('vectorNamespace').value.trim();if($('activeToggle'))form.active=$('activeToggle').checked;form.allowedMedia=qsa('[data-media]:checked').map(x=>x.dataset.media);form.tools=qsa('[data-tool]:checked').map(x=>x.dataset.tool)}
function renderAll(){tabs();renderPanel();renderCharacterList();fillSelect();if($('characterSelect'))$('characterSelect').value=current||''}
function renderPanel(){const h=$('panel');if(!h)return;if(tab==='identite')h.innerHTML=`<div class="card"><h2>Identité complète</h2><div class="section-note">Cette fiche définit qui est le personnage, indépendamment des portails et des formations qu’il enseigne.</div><div class="grid">${inp('name','Nom affiché')}${inp('code','Code agent / cerveau','input','Stable : ex. keven, lena, celeste.')}${inp('visibleRole','Rôle visible / sous-titre')}${inp('shortDescription','Description courte','textarea')}${inp('biography','Biographie / histoire du personnage','textarea')}<div class="full"><label>Actif</label><label class="chip"><input id="activeToggle" type="checkbox" ${form.active!==false?'checked':''}> Personnage actif</label></div></div></div>`;
else if(tab==='mission')h.innerHTML=`<div class="card"><h2>Mission & intelligence</h2><div class="grid">${inp('mission','Mission / raison d’exister','textarea')}${inp('systemPrompt','Prompt système complet','textarea','Règles permanentes du personnage. Peut être très détaillé.')}</div></div>`;
else if(tab==='personnalite')h.innerHTML=`<div class="card"><h2>Personnalité & langage</h2><div class="grid">${inp('personality','Personnalité','textarea')}${inp('values','Valeurs','textarea')}${inp('tone','Ton','textarea')}${inp('languageStyle','Style de langage','textarea')}${inp('favoriteExpressions','Expressions favorites','textarea')}${inp('avoidExpressions','Expressions / formulations à éviter','textarea')}</div></div>`;
else if(tab==='expertise')h.innerHTML=`<div class="card"><h2>Expertise, pédagogie & limites</h2><div class="grid">${inp('expertise','Domaines d’expertise','textarea')}${inp('skills','Compétences','textarea')}${inp('methods','Méthodes / pratiques','textarea')}${inp('teachingStyle','Style pédagogique','textarea')}${inp('ethics','Cadre éthique','textarea')}${inp('limits','Limites professionnelles','textarea')}${inp('canDo','Ce qu’il peut faire','textarea')}${inp('cannotDo','Ce qu’il ne doit jamais faire','textarea')}</div></div>`;
else if(tab==='presence')h.innerHTML=`<div class="card"><h2>Accueil & présence dans le chat</h2><div class="grid">${inp('welcomeMessage','Message d’accueil','textarea')}<div class="full"><label>Suggestions de départ — une par ligne</label><textarea id="suggestions">${esc((form.suggestions||[]).join('\n'))}</textarea></div></div></div>`;
else if(tab==='voix')renderVoice();else if(tab==='formation')renderFormations();else if(tab==='cerveau')renderBrain();else if(tab==='portails')renderPortals();else if(tab==='notes')renderNotes();}
function renderVoice(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Voix & médias</h2><div class="grid">${inp('image','Image / avatar URL')}${inp('welcomeVideo','Vidéo d’accueil URL')}${inp('voiceName','Nom lisible de la voix')}${inp('voiceId','Voice ID ElevenLabs')}${inp('voiceNotes','Notes de voix','textarea')}<div class="full preview">${form.image?`<img class="avatar" src="${esc(form.image)}" alt="${esc(form.name)}">`:''}<div><button class="btn" id="testVoice">🔊 Tester la voix</button><div class="hint">Teste directement le Voice ID de cette fiche.</div></div></div><div class="full"><label>Médias que le personnage peut remettre</label><div class="chips">${MEDIA.map(m=>`<label class="chip"><input data-media="${m}" type="checkbox" ${(form.allowedMedia||[]).includes(m)?'checked':''}> ${m}</label>`).join('')}</div></div><div class="full"><h3>Ressources autorisées</h3><div id="resources" class="resources-table"></div><button id="addResource" class="btn small" type="button">＋ Ajouter une ressource</button></div></div></div>`;renderResources();$('addResource').onclick=()=>{collectResources();form.resources.push({type:'PDF',title:'',url:''});renderVoice()};$('testVoice').onclick=testVoice}
function collectResources(){const rows=qsa('[data-resource]');if(!rows.length)return;form.resources=rows.map(r=>({type:r.querySelector('[data-r="type"]').value,title:r.querySelector('[data-r="title"]').value,url:r.querySelector('[data-r="url"]').value})).filter(x=>x.title||x.url)}
function renderResources(){const h=$('resources');if(!h)return;const r=form.resources||[];h.innerHTML=r.length?r.map((x,i)=>`<div class="resource-row" data-resource><select data-r="type">${['PDF','AUDIO','VIDEO','IMAGE','LINK','CANVA'].map(t=>`<option ${x.type===t?'selected':''}>${t}</option>`).join('')}</select><input data-r="title" value="${esc(x.title||'')}" placeholder="Titre"><input data-r="url" value="${esc(x.url||'')}" placeholder="https://..."><button class="btn danger small" data-del-resource="${i}">Retirer</button></div>`).join(''):'<div class="empty">Aucune ressource enregistrée.</div>';qsa('[data-del-resource]').forEach(b=>b.onclick=()=>{collectResources();form.resources.splice(Number(b.dataset.delResource),1);renderVoice()})}
async function testVoice(){collect();if(!form.voiceId)return status('Ajoute d’abord le Voice ID ElevenLabs.','err');status('Test de la voix…');try{const r=await fetch('/api/superadmin4/personnages/tts',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:form.code||current,voiceId:form.voiceId,text:'Bonjour, je suis '+(form.name||'ton personnage')+'. Voici un test de ma voix.'})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||'Test impossible')}const url=URL.createObjectURL(await r.blob());new Audio(url).play();status('Voix lancée.','ok')}catch(e){status(e.message,'err')}}
function renderFormations(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Formation Vivante de ${esc(form.name||current||'ce personnage')}</h2><div class="section-note">Même système central : toute formation enregistrée ici utilise les clés Formation Vivante existantes. Rien n’est dupliqué.</div><div class="formation-toolbar"><div><label>Portail</label><input id="formationPortal" value="${esc(form.primaryPortal||'diane')}" placeholder="diane, praticiens, lena…"></div><div><label>Formation</label><select id="formationSelect"><option value="">— Nouvelle formation —</option>${formations.map(f=>`<option value="${esc(f.key)}">${esc(f.title)} · ${esc(f.portal)}</option>`).join('')}</select></div><button class="btn" id="newFormation">＋ Nouvelle</button></div><div id="formationEditor"></div></div>`;$('formationSelect').onchange=()=>loadFormation($('formationSelect').value);$('newFormation').onclick=()=>{activeFormation={id:'',titre:'',description:'',ordre:0,portail:$('formationPortal').value||form.primaryPortal||'diane',modules:[]};renderFormationEditor()};if(activeFormation)renderFormationEditor();else $('formationEditor').innerHTML='<div class="empty">Choisis une formation ou crée-en une nouvelle.</div>'}
async function loadFormation(key){const meta=formations.find(f=>f.key===key);if(!meta){activeFormation=null;renderFormations();return}try{const d=await api('/api/formations?agent='+encodeURIComponent(current)+'&portail='+encodeURIComponent(meta.portal));activeFormation=(d.formations||[]).find(x=>x.id===meta.id)||null;renderFormationEditor()}catch(e){status(e.message,'err')}}
function renderFormationEditor(){const h=$('formationEditor');if(!h||!activeFormation)return;const f=activeFormation;h.innerHTML=`<div class="formation-editor"><div class="grid3"><div><label>Titre</label><input id="foTitle" value="${esc(f.titre||'')}"></div><div><label>Portail</label><input id="foPortal" value="${esc(f.portail||$('formationPortal')?.value||form.primaryPortal||'diane')}"></div><div><label>Ordre</label><input id="foOrder" type="number" value="${Number(f.ordre||0)}"></div><div class="full"><label>Description</label><textarea id="foDesc">${esc(f.description||'')}</textarea></div></div><div id="modules"></div><div class="actions-row"><button class="btn" id="addModule">＋ Module</button><button class="btn primary" id="saveFormation">💾 Enregistrer la formation</button>${f.id?'<button class="btn danger" id="deleteFormation">Supprimer la formation</button>':''}</div></div>`;renderModules();$('addModule').onclick=()=>{collectFormation();f.modules=f.modules||[];f.modules.push({id:'m'+(f.modules.length+1),numero:f.modules.length+1,titre:'Module '+(f.modules.length+1),blocs:[]});renderFormationEditor()};$('saveFormation').onclick=saveFormation;if($('deleteFormation'))$('deleteFormation').onclick=deleteFormation}
function renderModules(){const h=$('modules');if(!h)return;const mods=activeFormation.modules||[];h.innerHTML=mods.length?mods.map((m,mi)=>`<div class="module-box" data-module="${mi}"><div class="module-head"><div><label>No</label><input data-m="numero" type="number" value="${Number(m.numero||mi+1)}"></div><div><label>Titre module</label><input data-m="titre" value="${esc(m.titre||'')}"></div><button class="btn danger small" data-del-module="${mi}">Retirer</button></div><div data-blocks="${mi}">${(m.blocs||[]).map((b,bi)=>blockHtml(b,mi,bi)).join('')}</div><button class="btn small" data-add-block="${mi}">＋ Bloc</button></div>`).join(''):'<div class="empty">Aucun module.</div>';qsa('[data-del-module]').forEach(b=>b.onclick=()=>{collectFormation();activeFormation.modules.splice(Number(b.dataset.delModule),1);renderFormationEditor()});qsa('[data-add-block]').forEach(b=>b.onclick=()=>{collectFormation();const m=activeFormation.modules[Number(b.dataset.addBlock)];m.blocs=m.blocs||[];m.blocs.push({type:'texte',contenu:''});renderFormationEditor()});qsa('[data-del-block]').forEach(b=>b.onclick=()=>{collectFormation();activeFormation.modules[Number(b.dataset.mi)].blocs.splice(Number(b.dataset.bi),1);renderFormationEditor()})}
function blockHtml(b,mi,bi){const type=b.type||'texte';let body='';if(type==='texte'||type==='intervention')body=`<textarea data-b="contenu">${esc(b.contenu||'')}</textarea>`;else if(type==='image')body=`<input data-b="url" value="${esc(b.url||'')}" placeholder="URL image"><input data-b="legende" value="${esc(b.legende||'')}" placeholder="Légende">`;else if(type==='audio'||type==='video')body=`<input data-b="url" value="${esc(b.url||'')}" placeholder="URL"><input data-b="titre" value="${esc(b.titre||'')}" placeholder="Titre"><textarea data-b="intro" placeholder="Introduction">${esc(b.intro||'')}</textarea>`;else if(type==='exercice')body=`<input data-b="objectif" value="${esc(b.objectif||'')}" placeholder="Objectif"><textarea data-b="consigne" placeholder="Consigne">${esc(b.consigne||'')}</textarea>`;else if(type==='lien')body=`<input data-b="url" value="${esc(b.url||'')}" placeholder="URL"><input data-b="titre" value="${esc(b.titre||'')}" placeholder="Titre"><textarea data-b="intro" placeholder="Introduction">${esc(b.intro||'')}</textarea>`;return `<div class="block-box" data-block data-mi="${mi}" data-bi="${bi}"><div class="block-head"><div><label>Type</label><select data-b="type">${['texte','image','audio','video','exercice','intervention','lien'].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Contenu</label>${body}</div><button class="btn danger small" data-del-block data-mi="${mi}" data-bi="${bi}">Retirer</button></div></div>`}
function collectFormation(){if(!activeFormation)return;activeFormation.titre=$('foTitle')?.value||activeFormation.titre||'';activeFormation.description=$('foDesc')?.value||'';activeFormation.portail=$('foPortal')?.value||$('formationPortal')?.value||form.primaryPortal||'diane';activeFormation.ordre=Number($('foOrder')?.value||0);const mods=[];qsa('[data-module]').forEach((el,mi)=>{const m={id:activeFormation.modules?.[mi]?.id||('m'+(mi+1)),numero:Number(el.querySelector('[data-m="numero"]').value||mi+1),titre:el.querySelector('[data-m="titre"]').value,blocs:[]};el.querySelectorAll('[data-block]').forEach(be=>{const b={};be.querySelectorAll('[data-b]').forEach(x=>b[x.dataset.b]=x.value);m.blocs.push(b)});mods.push(m)});activeFormation.modules=mods}
async function saveFormation(){collectFormation();if(!current)return status('Enregistre d’abord le personnage.','err');try{const d=await api('/api/formations/save',{method:'POST',body:JSON.stringify({agent:current,portail:activeFormation.portail,formation:activeFormation})});activeFormation=d.formation;await refreshRelated();renderFormations();status('Formation enregistrée.','ok')}catch(e){status(e.message,'err')}}
async function deleteFormation(){if(!activeFormation?.id||!confirm('Supprimer cette formation ?'))return;try{await api('/api/formations/delete',{method:'POST',body:JSON.stringify({agent:current,portail:activeFormation.portail,id:activeFormation.id})});activeFormation=null;await refreshRelated();renderFormations();status('Formation supprimée.','ok')}catch(e){status(e.message,'err')}}
function renderBrain(){const b=brain||{};const h=$('panel');h.innerHTML=`<div class="card"><h2>Cerveau & connaissances</h2><div class="grid"><div><label>Namespace</label><input id="vectorNamespace" value="${esc(form.vectorNamespace||current||form.code||'')}"></div><div><label>État</label><div class="hint">Vectorize : ${b.bindings?.vectorize?'actif':'non détecté'} · AI : ${b.bindings?.ai?'actif':'non détecté'}</div></div><div class="full brain-stats"><div class="stat"><span>Fragments</span><b>${Number(b.vectors||0)}</b></div><div class="stat"><span>Sources</span><b>${(b.sources||[]).length}</b></div><div class="stat"><span>Personnage</span><b>${esc(current||'—')}</b></div></div><div class="full"><h3>Sources</h3><div class="list">${(b.sources||[]).length?(b.sources||[]).map(s=>`<div class="item"><span>${esc(s.source)}</span><span class="badge">${s.chunks} fragments</span></div>`).join(''):'<div class="empty">Aucune connaissance vectorisée.</div>'}</div></div><div class="full"><h3>Ajouter des connaissances</h3><div class="grid"><div><label>Nom de la source</label><input id="brainSource" placeholder="Ex. Manuel chamanisme — Module 1"></div><div class="full"><label>Texte à ingérer</label><textarea id="brainText" style="min-height:220px"></textarea></div></div><div class="actions-row"><button class="btn primary" id="brainIngest">🧠 Ajouter au cerveau</button><button class="btn danger" id="brainWipe">Effacer le cerveau de ce personnage</button></div></div></div></div>`;$('brainIngest').onclick=ingestBrain;$('brainWipe').onclick=wipeBrain}
async function ingestBrain(){const text=$('brainText').value.trim(),source=$('brainSource').value.trim()||'source';if(!current||!text)return status('Personnage et texte requis.','err');status('Vectorisation…');try{await api('/api/vectorize/ingest',{method:'POST',body:JSON.stringify({agent:current,source,text})});await refreshRelated();renderBrain();status('Connaissances ajoutées.','ok')}catch(e){status(e.message,'err')}}
async function wipeBrain(){if(!current)return;if(!confirm('ATTENTION : effacer tout le cerveau vectoriel de '+(form.name||current)+' ?'))return;if(!confirm('Dernière confirmation : cette action supprime les fragments vectorisés de ce personnage.'))return;try{await api('/api/vectorize/wipe',{method:'POST',body:JSON.stringify({agent:current})});await refreshRelated();renderBrain();status('Cerveau vectoriel vidé.','ok')}catch(e){status(e.message,'err')}}
function renderPortals(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Portails & outils</h2><div class="grid"><div><label>Portail principal</label><input id="primaryPortal" value="${esc(form.primaryPortal||'')}" placeholder="diane, praticiens, lena…"></div><div><label>Outils autorisés</label><div class="chips">${TOOLS.map(t=>`<label class="chip"><input data-tool="${t}" type="checkbox" ${(form.tools||[]).includes(t)?'checked':''}> ${t}</label>`).join('')}</div></div><div class="full"><label>Portails existants</label><div class="list">${portals.length?portals.map(p=>`<label class="item"><span><input data-portal="${esc(p.id)}" data-title="${esc(p.title||p.id)}" type="checkbox" ${(form.portalAssignments||[]).some(x=>x.id===p.id)?'checked':''}> <strong>${esc(p.title||p.id)}</strong></span><span class="hint">${esc(p.id)}</span></label>`).join(''):'<div class="empty">Aucun projet de portail trouvé.</div>'}</div></div></div></div>`;qsa('[data-portal]').forEach(cb=>cb.onchange=()=>{const id=cb.dataset.portal;form.portalAssignments=form.portalAssignments||[];const i=form.portalAssignments.findIndex(x=>x.id===id);if(cb.checked&&i<0)form.portalAssignments.push({id,title:cb.dataset.title,role:'specialiste'});if(!cb.checked&&i>=0)form.portalAssignments.splice(i,1)})}
function renderNotes(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Notes internes & versions</h2><div class="grid"><div class="full"><label>Notes internes admin</label><textarea id="f-internalNotes">${esc(form.internalNotes||'')}</textarea></div><div class="full"><label>Tags — séparés par virgules</label><input id="tags" value="${esc((form.tags||[]).join(', '))}"></div><div class="full"><h3>Historique des versions</h3><div class="list">${history.length?history.map(x=>`<div class="item"><div class="meta"><strong>Version ${Number(x.version||0)}</strong><span class="hint">${esc(x.updatedAt||'')}</span></div><button class="btn small" data-restore="${esc(x.key)}">Restaurer</button></div>`).join(''):'<div class="empty">Aucune ancienne version.</div>'}</div></div></div></div>`;qsa('[data-restore]').forEach(b=>b.onclick=()=>restoreVersion(b.dataset.restore))}
async function restoreVersion(key){if(!current||!confirm('Restaurer cette version ? La version actuelle sera conservée dans l’historique.'))return;try{const d=await api('/api/superadmin4/personnages/history/restore',{method:'POST',body:JSON.stringify({code:current,key})});form=normalize(d.profile);profiles[current]=form;await refreshRelated();renderAll();status('Version restaurée.','ok')}catch(e){status(e.message,'err')}}
async function saveCharacter(){collect();collectResources();form.code=slug(form.code||form.name||current);if(!form.name||!form.code)return status('Nom et code requis.','err');status('Enregistrement…');try{await api('/api/personnages/save',{method:'POST',body:JSON.stringify({nom:form.name,code:form.code,portail:form.primaryPortal||''})});const d=await api('/api/superadmin4/personnages/profile',{method:'POST',body:JSON.stringify({...form,sub:form.visibleRole,prompt:form.mission,greeting:form.welcomeMessage,portail:form.primaryPortal})});current=form.code;form=normalize(d.profile);profiles[current]=form;await loadAll();await refreshRelated();renderAll();status('Personnage enregistré dans la KV centrale.','ok')}catch(e){status(e.message,'err')}}
function bind(){if($('saveBtn'))$('saveBtn').onclick=saveCharacter;if($('newBtn'))$('newBtn').onclick=newCharacter;if($('characterSelect'))$('characterSelect').onchange=e=>e.target.value?openCharacter(e.target.value):newCharacter();if($('search'))$('search').oninput=renderCharacterList}
document.addEventListener('DOMContentLoaded',async()=>{if(!(await auth()))return;form=blank();bind();await loadAll();renderAll()});
})();
