(()=>{'use strict';
const $=id=>document.getElementById(id);const qsa=s=>[...document.querySelectorAll(s)];
let catalog=[],profiles={},current='',form={},history=[],formations=[],portals=[],brain=null,activeFormation=null,tab='identite';
const MEDIA=['VIDEO','AUDIO','IMAGE','PDF','LINK','CANVA','IMAGE_GENERATE'];
const TOOLS=['formation-vivante','vector-brain','image-generation','web-links','pdf','audio','video','canva'];
const TABS=[['identite','Identité'],['mission','Mission & prompt'],['personnalite','Personnalité'],['expertise','Expertise & limites'],['presence','Accueil & présence'],['voix','Voix & médias'],['formation','Formation Vivante'],['cerveau','Cerveau'],['portails','Portails & outils'],['notes','Notes & versions']];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slug(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)}
async function api(path,opt={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(r.status===401){location.href='/';throw Error('Session expirée.')}if(!r.ok)throw Error(d.error||d.message||('Erreur '+r.status));return d}
function blank(){return{schemaVersion:4,code:'',name:'',visibleRole:'',shortDescription:'',biography:'',mission:'',systemPrompt:'',personality:'',values:'',tone:'',languageStyle:'',favoriteExpressions:'',avoidExpressions:'',expertise:'',skills:'',methods:'',teachingStyle:'',ethics:'',limits:'',canDo:'',cannotDo:'',welcomeMessage:'',suggestions:[],image:'',welcomeVideo:'',voiceName:'',voiceId:'',voiceNotes:'',modelPrimary:'',modelFallback:'',primaryPortal:'',portalAssignments:[],formationRefs:[],vectorNamespace:'',resources:[],allowedMedia:[...MEDIA],tools:[...TOOLS],internalNotes:'',tags:[],active:true}}
function normalize(p={}){const b=blank();return{...b,...p,code:slug(p.code||p.id||p.name),name:p.name||p.nom||'',visibleRole:p.visibleRole||p.sub||'',mission:p.mission||p.prompt||'',systemPrompt:p.systemPrompt||'',welcomeMessage:p.welcomeMessage||p.greeting||'',primaryPortal:p.primaryPortal||p.portail||'',suggestions:Array.isArray(p.suggestions)?p.suggestions:[],tags:Array.isArray(p.tags)?p.tags:[],resources:Array.isArray(p.resources)?p.resources:[],allowedMedia:Array.isArray(p.allowedMedia)&&p.allowedMedia.length?p.allowedMedia:[...MEDIA],tools:Array.isArray(p.tools)?p.tools:[...TOOLS],portalAssignments:Array.isArray(p.portalAssignments)?p.portalAssignments:[]}}
function status(t,k=''){const e=$('status');e.textContent=t;e.className='status '+k}
async function auth(){try{const d=await api('/api/check-auth',{method:'POST',body:'{}'});if(!d.valid){location.href='/';return false}return true}catch(_){location.href='/';return false}}
async function loadAll(){status('Chargement…');const [c,pj]=await Promise.all([api('/api/personnages'),api('/api/portals').catch(()=>({portals:[]}))]);catalog=c.personnages||c.agents||[];portals=(pj.portals||[]).filter(p=>p&&p.id&&p.active!==false);const pf=await api('/api/superadmin4/personnages/profile').catch(()=>({profiles:[]}));profiles=Object.fromEntries((pf.profiles||[]).map(x=>[x.code,x]));renderCharacterList();fillSelect();status('Prêt.','ok')}
function renderCharacterList(){const host=$('characterList');if(!host)return;const search=($('search')?.value||'').toLowerCase().trim();const rows=catalog.map(c=>{const p=normalize(profiles[c.code]||{code:c.code,name:c.nom,primaryPortal:c.portail});return{...c,p}}).filter(x=>!search||(`${x.nom} ${x.code} ${x.p.visibleRole} ${(x.p.tags||[]).join(' ')}`).toLowerCase().includes(search));host.innerHTML=rows.length?rows.map(x=>`<div class="character-card ${current===x.code?'active':''}" data-code="${esc(x.code)}">${x.p.image?`<img src="${esc(x.p.image)}" alt="">`:`<span style="width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#0f1c3f">✦</span>`}<div><strong>${esc(x.nom)}</strong><div class="hint">${esc(x.p.visibleRole||x.code)}</div></div></div>`).join(''):'<div class="empty">Aucun personnage.</div>';qsa('[data-code]').forEach(x=>x.onclick=()=>openCharacter(x.dataset.code))}
function fillSelect(){const s=$('characterSelect');if(!s)return;s.innerHTML='<option value="">— Choisir un personnage —</option>'+catalog.map(c=>`<option value="${esc(c.code)}">${esc(c.nom)}${c.portail?' · '+esc(c.portail):''}</option>`).join('');if(current)s.value=current}
async function openCharacter(code){collect();current=slug(code);const base=catalog.find(x=>x.code===current)||{};const d=await api('/api/superadmin4/personnages/profile?code='+encodeURIComponent(current)).catch(()=>({profile:null}));form=normalize(d.profile||profiles[current]||{code:current,name:base.nom,primaryPortal:base.portail});profiles[current]=form;await refreshRelated();renderAll();status('Fiche chargée.','ok')}
async function refreshRelated(){if(!current){history=[];formations=[];brain=null;return}const [h,f,b]=await Promise.all([api('/api/superadmin4/personnages/history?code='+encodeURIComponent(current)).catch(()=>({history:[]})),api('/api/superadmin4/personnages/formations?code='+encodeURIComponent(current)).catch(()=>({formations:[]})),api('/api/vectorize/stats?agent='+encodeURIComponent(current)).catch(()=>({data:{}}))]);history=h.history||[];formations=f.formations||[];brain=b.data||b.brain||{};}
function newCharacter(){collect();current='';form=blank();history=[];formations=[];brain=null;activeFormation=null;fillSelect();renderCharacterList();renderAll();status('Nouvelle fiche.')}
function tabs(){const h=$('tabs');h.innerHTML=TABS.map(([k,l])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${l}</button>`).join('');qsa('[data-tab]').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;tabs();renderPanel()})}
function inp(k,label,type='input',hint=''){const v=form[k]??'';return `<div class="${type==='textarea'?'full large':''}"><label>${esc(label)}</label>${type==='textarea'?`<textarea id="f-${k}">${esc(v)}</textarea>`:`<input id="f-${k}" value="${esc(v)}">`}${hint?`<div class="hint">${esc(hint)}</div>`:''}</div>`}
function collect(){qsa('[id^="f-"]').forEach(el=>form[el.id.slice(2)]=el.value);collectSuggestions();if($('tags'))form.tags=$('tags').value.split(',').map(x=>x.trim()).filter(Boolean);if($('primaryPortal'))form.primaryPortal=$('primaryPortal').value.trim();if($('vectorNamespace'))form.vectorNamespace=$('vectorNamespace').value.trim();if($('activeToggle'))form.active=$('activeToggle').checked;form.allowedMedia=qsa('[data-media]:checked').map(x=>x.dataset.media);form.tools=qsa('[data-tool]:checked').map(x=>x.dataset.tool)}
function renderAll(){tabs();renderPanel();renderCharacterList();fillSelect();if($('characterSelect'))$('characterSelect').value=current||''}
function renderPanel(){const h=$('panel');if(!h)return;if(tab==='identite')h.innerHTML=`<div class="card"><h2>Identité complète</h2><div class="section-note">Cette fiche définit qui est le personnage, indépendamment des portails et des formations qu’il enseigne.</div><div class="grid">${inp('name','Nom affiché')}${inp('code','Code agent / cerveau','input','Stable : ex. keven, lena, celeste.')}${inp('visibleRole','Rôle visible / sous-titre')}${inp('shortDescription','Description courte','textarea')}${inp('biography','Biographie / histoire du personnage','textarea')}<div class="full"><label>Actif</label><label class="chip"><input id="activeToggle" type="checkbox" ${form.active!==false?'checked':''}> Personnage actif</label></div></div></div>`;
else if(tab==='mission')h.innerHTML=`<div class="card"><h2>Mission & intelligence</h2><div class="grid">${inp('mission','Mission / raison d’exister','textarea')}${inp('systemPrompt','Prompt système complet','textarea','Règles permanentes du personnage. Peut être très détaillé.')}</div></div>`;
else if(tab==='personnalite')h.innerHTML=`<div class="card"><h2>Personnalité & langage</h2><div class="grid">${inp('personality','Personnalité','textarea')}${inp('values','Valeurs','textarea')}${inp('tone','Ton','textarea')}${inp('languageStyle','Style de langage','textarea')}${inp('favoriteExpressions','Expressions favorites','textarea')}${inp('avoidExpressions','Expressions / formulations à éviter','textarea')}</div></div>`;
else if(tab==='expertise')h.innerHTML=`<div class="card"><h2>Expertise, pédagogie & limites</h2><div class="grid">${inp('expertise','Domaines d’expertise','textarea')}${inp('skills','Compétences','textarea')}${inp('methods','Méthodes / pratiques','textarea')}${inp('teachingStyle','Style pédagogique','textarea')}${inp('ethics','Cadre éthique','textarea')}${inp('limits','Limites professionnelles','textarea')}${inp('canDo','Ce qu’il peut faire','textarea')}${inp('cannotDo','Ce qu’il ne doit jamais faire','textarea')}</div></div>`;
else if(tab==='presence')renderPresence();
else if(tab==='voix')renderVoice();else if(tab==='formation')renderFormations();else if(tab==='cerveau')renderBrain();else if(tab==='portails')renderPortals();else if(tab==='notes')renderNotes();}

const NYXIA_TRIGGER_PREFIX='@NYXIA_TRIGGER:';
const SUGGESTION_ACTIONS=[
  {v:'chat',label:'💬 Conversation'},
  {v:'video',label:'🎥 Vidéo'},
  {v:'audio',label:'🎧 MP3'},
  {v:'pdf',label:'📄 PDF'},
  {v:'link',label:'🔗 Lien'},
  {v:'canva',label:'🎨 Canva'}
];
function decodeStoredSuggestion(raw){
  if(raw&&typeof raw==='object')return{label:String(raw.label||raw.text||raw.title||''),action:String(raw.action||raw.type||'chat'),message:String(raw.message||raw.value||''),url:String(raw.url||''),intro:String(raw.intro||''),resourceTitle:String(raw.resourceTitle||raw.resource||'')};
  const text=String(raw||'').trim();if(!text)return null;
  if(text.startsWith(NYXIA_TRIGGER_PREFIX)){try{const x=JSON.parse(text.slice(NYXIA_TRIGGER_PREFIX.length));return{label:String(x.l||x.label||''),action:String(x.a||x.action||'chat'),message:String(x.m||x.message||''),url:String(x.u||x.url||''),intro:String(x.i||x.intro||''),resourceTitle:String(x.r||x.resourceTitle||'')}}catch(_){}}
  return{label:text,action:'chat',message:text,url:'',intro:'',resourceTitle:''};
}
function suggestionObjects(){return(form.suggestions||[]).map(decodeStoredSuggestion).filter(Boolean)}
function encodeSuggestion(x){
  const action=String(x.action||'chat').toLowerCase();
  const label=String(x.label||'').trim();
  if(!label)return'';
  if(action==='chat'&&String(x.message||'').trim()===label&&!x.url&&!x.intro&&!x.resourceTitle)return label;
  const data={l:label,a:action};
  if(String(x.message||'').trim())data.m=String(x.message).trim();
  if(String(x.url||'').trim())data.u=String(x.url).trim();
  if(String(x.intro||'').trim())data.i=String(x.intro).trim();
  if(String(x.resourceTitle||'').trim())data.r=String(x.resourceTitle).trim();
  return NYXIA_TRIGGER_PREFIX+JSON.stringify(data);
}
function compatibleResources(action){
  const map={video:['VIDEO'],audio:['AUDIO'],pdf:['PDF'],link:['LINK'],canva:['CANVA']};
  const wanted=map[action]||[];
  return(form.resources||[]).filter(r=>r&&wanted.includes(String(r.type||'').toUpperCase())&&r.title);
}
function collectSuggestions(){
  const rows=qsa('[data-suggestion-row]');
  if(!rows.length)return;
  form.suggestions=rows.map(row=>{
    const action=row.querySelector('[data-s="action"]')?.value||'chat';
    const res=row.querySelector('[data-s="resource"]')?.value||'';
    const resObj=(form.resources||[]).find(r=>String(r.title||'')===res);
    return encodeSuggestion({
      label:row.querySelector('[data-s="label"]')?.value||'',
      action,
      message:row.querySelector('[data-s="message"]')?.value||'',
      url:(resObj&&resObj.url)||row.querySelector('[data-s="url"]')?.value||'',
      intro:row.querySelector('[data-s="intro"]')?.value||'',
      resourceTitle:res
    });
  }).filter(Boolean).slice(0,30);
}
function renderPresence(){
  const h=$('panel');
  h.innerHTML=`<div class="card"><h2>Accueil & présence dans le chat</h2><div class="grid">${inp('welcomeMessage','Message d’accueil','textarea')}<div class="full"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><label>Suggestions de départ</label><div class="hint">Chaque bouton peut lancer une conversation ou remettre directement une vidéo, un MP3, un PDF, un lien ou une présentation Canva.</div></div><button class="btn" id="addSuggestion" type="button">＋ Ajouter un déclencheur</button></div><div id="suggestionRows" style="margin-top:12px"></div></div></div></div>`;
  renderSuggestionRows();
  $('addSuggestion').onclick=()=>{collectSuggestions();form.suggestions=form.suggestions||[];form.suggestions.push(encodeSuggestion({label:'Nouveau bouton',action:'chat',message:'Nouveau bouton'}));renderSuggestionRows()};
}
function suggestionRowHtml(x,i){
  const action=String(x.action||'chat').toLowerCase();
  const resources=compatibleResources(action);
  const resourceOptions=['<option value="">— URL / message manuel —</option>'].concat(resources.map(r=>`<option value="${esc(r.title)}" ${String(x.resourceTitle||'')===String(r.title)?'selected':''}>${esc(r.title)}</option>`)).join('');
  const isChat=action==='chat';
  const urlLabel=action==='video'?'URL vidéo':action==='audio'?'URL MP3':action==='pdf'?'URL PDF':action==='canva'?'URL Canva':'URL du lien';
  return `<div class="resource-row" data-suggestion-row data-si="${i}" style="margin-bottom:12px">
    <div><label>Texte du bouton</label><input data-s="label" value="${esc(x.label||'')}" placeholder="Ex. 🎥 Voir la démonstration"></div>
    <div><label>Déclencheur</label><select data-s="action">${SUGGESTION_ACTIONS.map(o=>`<option value="${o.v}" ${action===o.v?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>
    ${isChat?`<div class="resource-usage"><label>Message envoyé au personnage</label><textarea data-s="message" placeholder="Ex. Commence mon initiation au pendule.">${esc(x.message||x.label||'')}</textarea><input data-s="url" type="hidden" value=""><input data-s="intro" type="hidden" value=""><input data-s="resource" type="hidden" value=""></div>`:`<div><label>Ressource enregistrée (optionnel)</label><select data-s="resource">${resourceOptions}</select><div class="hint">Choisis une ressource de « Voix & médias », ou laisse vide pour coller une URL.</div></div><div><label>${esc(urlLabel)}</label><input data-s="url" value="${esc(x.url||'')}" placeholder="https://..."></div><div class="resource-usage"><label>Phrase d’accompagnement (optionnelle)</label><textarea data-s="intro" placeholder="Ex. Je te laisse ton cahier juste ici ✨">${esc(x.intro||'')}</textarea><input data-s="message" type="hidden" value=""></div>`}
    <div class="resource-remove"><div class="actions-row" style="margin:0;flex-wrap:nowrap"><button class="btn small" data-sug-up="${i}" type="button">↑</button><button class="btn small" data-sug-down="${i}" type="button">↓</button><button class="btn danger small" data-del-suggestion="${i}" type="button">Retirer</button></div></div>
  </div>`;
}
function renderSuggestionRows(){
  const host=$('suggestionRows');if(!host)return;
  const list=suggestionObjects();
  host.innerHTML=list.length?list.map(suggestionRowHtml).join(''):'<div class="empty">Aucun déclencheur de départ. Ajoute le premier bouton.</div>';
  qsa('[data-s="action"]').forEach(s=>s.onchange=()=>{collectSuggestions();renderSuggestionRows()});
  qsa('[data-s="resource"]').forEach(s=>s.onchange=()=>{
    const row=s.closest('[data-suggestion-row]'),title=s.value,res=(form.resources||[]).find(r=>String(r.title||'')===String(title));
    if(res&&row){const u=row.querySelector('[data-s="url"]');if(u)u.value=res.url||''}
  });
  qsa('[data-del-suggestion]').forEach(b=>b.onclick=()=>{collectSuggestions();const a=suggestionObjects();a.splice(Number(b.dataset.delSuggestion),1);form.suggestions=a.map(encodeSuggestion);renderSuggestionRows()});
  qsa('[data-sug-up]').forEach(b=>b.onclick=()=>moveSuggestion(Number(b.dataset.sugUp),-1));
  qsa('[data-sug-down]').forEach(b=>b.onclick=()=>moveSuggestion(Number(b.dataset.sugDown),1));
}
function moveSuggestion(i,dir){
  collectSuggestions();const a=suggestionObjects(),j=i+dir;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];form.suggestions=a.map(encodeSuggestion);renderSuggestionRows();
}

function renderVoice(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Voix, modèle IA & ressources</h2><div class="section-note">Tu configures ici ce que le personnage peut remettre dans le chat. Aucun marqueur technique à écrire.</div><div class="grid">${inp('image','Image / avatar URL')}${inp('welcomeVideo','Vidéo d’accueil URL')}${inp('voiceName','Nom lisible de la voix')}${inp('voiceId','Voice ID ElevenLabs')}${inp('voiceNotes','Notes de voix','textarea')}<div><label>Modèle IA principal</label><input id="f-modelPrimary" list="ai-model-presets" value="${esc(form.modelPrimary||'')}" placeholder="Vide = modèle par défaut du portail"><div class="hint">Tu peux coller n’importe quel ID de modèle OpenRouter.</div></div><div><label>Modèle IA de secours</label><input id="f-modelFallback" list="ai-model-presets" value="${esc(form.modelFallback||'')}" placeholder="Vide = secours par défaut"><div class="hint">Utilisé seulement si le modèle principal ne répond pas.</div></div><datalist id="ai-model-presets"><option value="deepseek/deepseek-v3.2"><option value="mistralai/mistral-small-3.2-24b-instruct"></datalist><div class="full preview">${form.image?`<img class="avatar" src="${esc(form.image)}" alt="${esc(form.name)}">`:''}<div><button class="btn" id="testVoice">🔊 Tester la voix</button><div class="hint">Teste directement le Voice ID de cette fiche.</div></div></div><div class="full"><label>Capacités média autorisées</label><div class="chips">${MEDIA.map(m=>`<label class="chip"><input data-media="${m}" type="checkbox" ${(form.allowedMedia||[]).includes(m)?'checked':''}> ${m}</label>`).join('')}</div></div><div class="full"><h3>🎁 Ressources & objets que le personnage peut remettre</h3><div class="hint" style="margin-bottom:10px">Vidéo YouTube / Google Drive, MP3, PDF, image, lien, Canva ou création d’image IA.</div><div id="resources" class="resources-table"></div><div class="actions-row"><button id="addVideo" class="btn small" type="button">＋ 🎥 Vidéo</button><button id="addAudio" class="btn small" type="button">＋ 🎧 MP3</button><button id="addPdf" class="btn small" type="button">＋ 📄 PDF</button><button id="addImage" class="btn small" type="button">＋ 🖼 Image</button><button id="addLink" class="btn small" type="button">＋ 🔗 Lien</button><button id="addCanva" class="btn small" type="button">＋ 🎨 Canva</button><button id="addImageGen" class="btn small" type="button">＋ ✨ Image IA</button></div></div></div></div>`;renderResources();const add=(type)=>{collectResources();form.resources.push({type,title:'',url:'',buttonLabel:'',usage:'',autoShare:true,prompt:''});renderVoice()};$('addVideo').onclick=()=>add('VIDEO');$('addAudio').onclick=()=>add('AUDIO');$('addPdf').onclick=()=>add('PDF');$('addImage').onclick=()=>add('IMAGE');$('addLink').onclick=()=>add('LINK');$('addCanva').onclick=()=>add('CANVA');$('addImageGen').onclick=()=>add('IMAGE_GENERATE');$('testVoice').onclick=testVoice}
function collectResources(){const rows=qsa('[data-resource]');if(!rows.length)return;form.resources=rows.map(r=>({type:r.querySelector('[data-r="type"]').value,title:r.querySelector('[data-r="title"]').value,url:(r.querySelector('[data-r="url"]')?.value||''),buttonLabel:r.querySelector('[data-r="buttonLabel"]').value,usage:r.querySelector('[data-r="usage"]').value,autoShare:!!r.querySelector('[data-r="autoShare"]').checked,prompt:(r.querySelector('[data-r="prompt"]')?.value||'')})).filter(x=>x.title||x.url||x.prompt)}
function renderResources(){const h=$('resources');if(!h)return;const r=form.resources||[];h.innerHTML=r.length?r.map((x,i)=>`<div class="resource-row" data-resource><div><label>Type</label><select data-r="type">${['PDF','AUDIO','VIDEO','IMAGE','LINK','CANVA','IMAGE_GENERATE'].map(t=>`<option ${x.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Titre</label><input data-r="title" value="${esc(x.title||'')}" placeholder="Ex. Consultation chamanique de groupe"></div><div><label>${x.type==='IMAGE_GENERATE'?'Description image IA':'URL HTTPS'}</label>${x.type==='IMAGE_GENERATE'?`<input data-r="prompt" value="${esc(x.prompt||x.url||'')}" placeholder="Ex. Illustration symbolique du voyage intérieur"><input data-r="url" type="hidden" value="">`:`<input data-r="url" value="${esc(x.url||'')}" placeholder="https://..."><input data-r="prompt" type="hidden" value="${esc(x.prompt||'')}">`}</div><div><label>Texte du bouton</label><input data-r="buttonLabel" value="${esc(x.buttonLabel||'')}" placeholder="Ex. 🎥 Voir la consultation"></div><div class="resource-usage"><label>Quand l’utiliser</label><textarea data-r="usage" placeholder="Ex. Quand la personne demande comment se déroule une séance à distance.">${esc(x.usage||'')}</textarea></div><div class="resource-auto"><label class="chip"><input data-r="autoShare" type="checkbox" ${x.autoShare!==false?'checked':''}> Peut la proposer spontanément</label></div><div class="resource-remove"><button class="btn danger small" data-del-resource="${i}" type="button">Retirer</button></div></div>`).join(''):'<div class="empty">Aucune ressource enregistrée.</div>';qsa('[data-del-resource]').forEach(b=>b.onclick=()=>{collectResources();form.resources.splice(Number(b.dataset.delResource),1);renderVoice()})}
async function testVoice(){collect();if(!form.voiceId)return status('Ajoute d’abord le Voice ID ElevenLabs.','err');status('Test de la voix…');try{const r=await fetch('/api/superadmin4/personnages/tts',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:form.code||current,voiceId:form.voiceId,text:'Bonjour, je suis '+(form.name||'ton personnage')+'. Voici un test de ma voix.'})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||'Test impossible')}const url=URL.createObjectURL(await r.blob());new Audio(url).play();status('Voix lancée.','ok')}catch(e){status(e.message,'err')}}
let formationEditId=null;
const FO_BLOCK_TYPES=[{v:'texte',label:'Texte'},{v:'image',label:'Image'},{v:'audio',label:'Audio MP3'},{v:'video',label:'Vidéo'},{v:'exercice',label:'Exercice'},{v:'intervention',label:'Intervention du personnage'},{v:'lien',label:'Lien (quiz, page, Google Forms…)'}];
function formationPortalChoices(selected){const list=(portals||[]).filter(p=>p&&p.id&&p.active!==false);if(selected&&!list.some(p=>String(p.id)===String(selected)))list.push({id:selected,name:selected,active:true});return list.map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(selected)?'selected':''}>${esc(p.name||p.id)}</option>`).join('')}
function currentFormationPortal(){return $('formationPortal')?.value||form.primaryPortal||(portals[0]?.id||'')}
function renderFormations(){const h=$('panel'),selected=form.primaryPortal||(portals[0]?.id||'');h.innerHTML=`<div class="card"><h2>Formation Vivante de ${esc(form.name||current||'ce personnage')}</h2><div class="section-note"><strong>Constructeur complet Formation Vivante.</strong> La formation est enregistrée pour un portail précis et pour ce personnage précis.</div>${!current?'<div class="empty" style="margin:14px 0">Tu peux préparer une nouvelle formation maintenant. Choisis simplement le personnage avant l’enregistrement.</div>':''}<div class="formation-toolbar"><div><label>Portail</label><select id="formationPortal">${formationPortalChoices(selected)}</select></div><button class="btn primary" id="newFormation">＋ Nouvelle formation</button></div><div id="formationList"><div class="empty">${current?'Chargement des formations…':'Choisis un personnage pour afficher ses formations existantes.'}</div></div><div id="formationEditor"></div></div>`;$('formationPortal').onchange=()=>{activeFormation=null;formationEditId=null;renderFormationEditor();if(current)loadFormationList()};$('newFormation').onclick=()=>{activeFormation={id:'',titre:'',description:'',ordre:0,portail:currentFormationPortal(),modules:[]};formationEditId=null;renderFormationEditor()};if(current)loadFormationList();if(activeFormation)renderFormationEditor()}
async function loadFormationList(){const box=$('formationList');if(!box||!current)return;box.innerHTML='<div class="empty">Chargement des formations…</div>';try{const portal=currentFormationPortal(),d=await api('/api/formations?agent='+encodeURIComponent(current)+'&portail='+encodeURIComponent(portal)),list=d.formations||[];if(!list.length){box.innerHTML='<div class="empty">Aucune formation sur ce portail.</div>';return}box.innerHTML=`<div class="list">${list.map(f=>`<div class="item" style="align-items:center"><div class="meta"><strong>${esc(f.titre||f.id)}</strong><span class="hint">${esc(f.id||'')} · ${(f.modules||[]).length} module(s) · ordre ${Number(f.ordre||0)}</span></div><div class="actions-row" style="margin:0"><button class="btn small" data-fo-edit="${esc(f.id)}">Modifier</button><button class="btn danger small" data-fo-delete="${esc(f.id)}">Supprimer</button></div></div>`).join('')}</div>`;qsa('[data-fo-edit]').forEach(x=>x.onclick=()=>loadFormationById(x.dataset.foEdit));qsa('[data-fo-delete]').forEach(x=>x.onclick=()=>deleteFormationById(x.dataset.foDelete))}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function loadFormationById(id){try{const portal=currentFormationPortal(),d=await api('/api/formations?agent='+encodeURIComponent(current)+'&portail='+encodeURIComponent(portal)),f=(d.formations||[]).find(x=>x.id===id);if(!f)return status('Formation introuvable.','err');activeFormation={id:f.id||'',titre:f.titre||'',description:f.description||'',ordre:Number(f.ordre||0),portail:portal,modules:(f.modules||[]).map((m,i)=>({id:m.id||('m'+(i+1)),numero:m.numero!=null?m.numero:i+1,titre:m.titre||('Module '+(i+1)),blocs:(m.blocs||[]).map(x=>({...blankFormationBlock(x.type),...x}))}))};formationEditId=f.id;renderFormationEditor()}catch(e){status(e.message,'err')}}
function blankFormationBlock(type='texte'){return{type,contenu:'',url:'',legende:'',titre:'',intro:'',objectif:'',consigne:''}}
function renderFormationEditor(){const h=$('formationEditor');if(!h)return;if(!activeFormation){h.innerHTML='';return}const f=activeFormation;h.innerHTML=`<div class="formation-editor" style="margin-top:16px"><div class="grid3"><div><label>Titre *</label><input id="foTitle" value="${esc(f.titre||'')}" placeholder="Ex. Développer son intuition"></div><div><label>Identifiant</label><input id="foId" value="${esc(f.id||'')}" placeholder="auto d’après le titre"></div><div><label>Ordre d’affichage</label><input id="foOrder" type="number" value="${Number(f.ordre||0)}"></div><div class="full"><label>Description</label><textarea id="foDesc">${esc(f.description||'')}</textarea></div></div><div style="margin-top:18px;display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap"><h3 style="margin:0">Modules</h3><button class="btn" id="addModule">➕ Ajouter un module</button></div><div id="modules"></div><div class="actions-row"><button class="btn primary" id="saveFormation">💾 Enregistrer la formation</button><button class="btn" id="cancelFormation">Annuler</button>${f.id?'<button class="btn danger" id="deleteFormation">Supprimer la formation</button>':''}</div></div>`;renderModules();$('addModule').onclick=()=>{collectFormation();const n=(activeFormation.modules||[]).length+1;activeFormation.modules.push({id:'m'+n,numero:n,titre:'Module '+n,blocs:[]});renderFormationEditor()};$('saveFormation').onclick=saveFormation;$('cancelFormation').onclick=()=>{activeFormation=null;formationEditId=null;renderFormationEditor()};if($('deleteFormation'))$('deleteFormation').onclick=()=>deleteFormationById(activeFormation.id)}
function renderModules(){const h=$('modules');if(!h||!activeFormation)return;const mods=activeFormation.modules||[];h.innerHTML=mods.length?mods.map((m,mi)=>`<div class="module-box" data-module="${mi}" style="margin-top:12px"><div class="module-head"><div style="flex:1"><label>Titre module</label><input data-m="titre" value="${esc(m.titre||'')}"></div><div class="actions-row" style="margin:0"><button class="btn small" data-mod-up="${mi}">↑</button><button class="btn small" data-mod-down="${mi}">↓</button><button class="btn danger small" data-del-module="${mi}">Retirer</button></div></div><div data-blocks="${mi}">${(m.blocs||[]).map((x,bi)=>blockHtml(x,mi,bi)).join('')}</div><button class="btn small" data-add-block="${mi}" style="margin-top:10px">➕ Ajouter un bloc</button></div>`).join(''):'<div class="empty" style="margin-top:12px">Aucun module. Ajoute ton premier module.</div>';qsa('[data-mod-up]').forEach(x=>x.onclick=()=>{collectFormation();moveFormationModule(Number(x.dataset.modUp),-1)});qsa('[data-mod-down]').forEach(x=>x.onclick=()=>{collectFormation();moveFormationModule(Number(x.dataset.modDown),1)});qsa('[data-del-module]').forEach(x=>x.onclick=()=>{collectFormation();activeFormation.modules.splice(Number(x.dataset.delModule),1);renumberFormationModules();renderFormationEditor()});qsa('[data-add-block]').forEach(x=>x.onclick=()=>{collectFormation();const m=activeFormation.modules[Number(x.dataset.addBlock)];m.blocs=m.blocs||[];m.blocs.push(blankFormationBlock('texte'));renderFormationEditor()});qsa('[data-del-block]').forEach(x=>x.onclick=()=>{collectFormation();activeFormation.modules[Number(x.dataset.mi)].blocs.splice(Number(x.dataset.bi),1);renderFormationEditor()});qsa('[data-block-up]').forEach(x=>x.onclick=()=>{collectFormation();moveFormationBlock(Number(x.dataset.mi),Number(x.dataset.bi),-1)});qsa('[data-block-down]').forEach(x=>x.onclick=()=>{collectFormation();moveFormationBlock(Number(x.dataset.mi),Number(x.dataset.bi),1)});qsa('[data-b="type"]').forEach(s=>s.onchange=()=>{collectFormation();const box=s.closest('[data-block]'),mi=Number(box.dataset.mi),bi=Number(box.dataset.bi);activeFormation.modules[mi].blocs[bi].type=s.value;renderFormationEditor()})}
function moveFormationModule(mi,dir){const x=activeFormation.modules,j=mi+dir;if(j<0||j>=x.length)return;[x[mi],x[j]]=[x[j],x[mi]];renumberFormationModules();renderFormationEditor()}
function renumberFormationModules(){(activeFormation.modules||[]).forEach((m,i)=>{m.numero=i+1;if(!m.id)m.id='m'+(i+1)})}
function moveFormationBlock(mi,bi,dir){const x=activeFormation.modules[mi].blocs,j=bi+dir;if(j<0||j>=x.length)return;[x[bi],x[j]]=[x[j],x[bi]];renderFormationEditor()}
function blockHtml(x,mi,bi){const type=x.type||'texte';let body='';if(type==='texte')body=`<textarea data-b="contenu" placeholder="Contenu de la leçon">${esc(x.contenu||'')}</textarea>`;else if(type==='intervention')body=`<textarea data-b="contenu" placeholder="Ce que le personnage dit / fait — tu peux écrire {prenom}">${esc(x.contenu||'')}</textarea>`;else if(type==='image')body=`<input data-b="url" value="${esc(x.url||'')}" placeholder="Adresse de l’image https://…"><input data-b="legende" value="${esc(x.legende||'')}" placeholder="Légende (optionnel)">`;else if(type==='audio')body=`<input data-b="url" value="${esc(x.url||'')}" placeholder="Adresse du MP3 https://…"><input data-b="titre" value="${esc(x.titre||'')}" placeholder="Titre (optionnel)"><textarea data-b="intro" placeholder="Intro suggérée (optionnel)">${esc(x.intro||'')}</textarea>`;else if(type==='video')body=`<input data-b="url" value="${esc(x.url||'')}" placeholder="Adresse vidéo YouTube, Vimeo, MP4…"><input data-b="titre" value="${esc(x.titre||'')}" placeholder="Titre (optionnel)"><textarea data-b="intro" placeholder="Intro suggérée (optionnel)">${esc(x.intro||'')}</textarea>`;else if(type==='exercice')body=`<input data-b="objectif" value="${esc(x.objectif||'')}" placeholder="Objectif (optionnel)"><textarea data-b="consigne" placeholder="Consigne">${esc(x.consigne||'')}</textarea>`;else if(type==='lien')body=`<input data-b="url" value="${esc(x.url||'')}" placeholder="Adresse du lien https://…"><input data-b="titre" value="${esc(x.titre||'')}" placeholder="Texte du bouton / titre"><textarea data-b="intro" placeholder="Phrase que le personnage dit">${esc(x.intro||'')}</textarea>`;return `<div class="block-box" data-block data-mi="${mi}" data-bi="${bi}"><div class="block-head"><div style="min-width:210px"><label>Type</label><select data-b="type">${FO_BLOCK_TYPES.map(o=>`<option value="${o.v}" ${type===o.v?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div><div class="actions-row" style="margin:0"><button class="btn small" data-block-up data-mi="${mi}" data-bi="${bi}">↑</button><button class="btn small" data-block-down data-mi="${mi}" data-bi="${bi}">↓</button><button class="btn danger small" data-del-block data-mi="${mi}" data-bi="${bi}">Retirer</button></div></div><div style="margin-top:8px"><label>Contenu</label>${body}</div></div>`}
function collectFormation(){if(!activeFormation)return;activeFormation.titre=$('foTitle')?.value||activeFormation.titre||'';activeFormation.id=$('foId')?.value.trim()||activeFormation.id||'';activeFormation.description=$('foDesc')?.value||'';activeFormation.portail=currentFormationPortal();activeFormation.ordre=Number($('foOrder')?.value||0);const mods=[];qsa('[data-module]').forEach((el,mi)=>{const m={id:activeFormation.modules?.[mi]?.id||('m'+(mi+1)),numero:mi+1,titre:el.querySelector('[data-m="titre"]').value,blocs:[]};el.querySelectorAll('[data-block]').forEach(be=>{const z={};be.querySelectorAll('[data-b]').forEach(v=>z[v.dataset.b]=v.value);m.blocs.push({...blankFormationBlock(z.type),...z})});mods.push(m)});activeFormation.modules=mods}
async function saveFormation(){collectFormation();if(!current)return status('Choisis d’abord un personnage.','err');if(!activeFormation?.titre?.trim())return status('Donne un titre à la formation.','err');try{const oldId=formationEditId,d=await api('/api/formations/save',{method:'POST',body:JSON.stringify({agent:current,portail:currentFormationPortal(),formation:activeFormation})});activeFormation=d.formation||activeFormation;if(oldId&&activeFormation.id&&oldId!==activeFormation.id){try{await api('/api/formations/delete',{method:'POST',body:JSON.stringify({agent:current,portail:currentFormationPortal(),id:oldId})})}catch(_){}}formationEditId=activeFormation.id||formationEditId;await refreshRelated();await loadFormationList();renderFormationEditor();status('Formation enregistrée.','ok')}catch(e){status(e.message,'err')}}
async function deleteFormationById(id){if(!id||!confirm('Supprimer cette formation ? Cette action est définitive.'))return;try{await api('/api/formations/delete',{method:'POST',body:JSON.stringify({agent:current,portail:currentFormationPortal(),id})});if(activeFormation?.id===id){activeFormation=null;formationEditId=null;renderFormationEditor()}await refreshRelated();await loadFormationList();status('Formation supprimée.','ok')}catch(e){status(e.message,'err')}}
function renderBrain(){const b=brain||{};const h=$('panel');h.innerHTML=`<div class="card"><h2>Cerveau & connaissances</h2><div class="grid"><div><label>Namespace</label><input id="vectorNamespace" value="${esc(form.vectorNamespace||current||form.code||'')}"></div><div><label>État</label><div class="hint">Vectorize : ${b.bindings?.vectorize?'actif':'non détecté'} · AI : ${b.bindings?.ai?'actif':'non détecté'}</div></div><div class="full brain-stats"><div class="stat"><span>Fragments</span><b>${Number(b.vectors||0)}</b></div><div class="stat"><span>Sources</span><b>${(b.sources||[]).length}</b></div><div class="stat"><span>Personnage</span><b>${esc(current||'—')}</b></div></div><div class="full"><h3>Sources</h3><div class="list">${(b.sources||[]).length?(b.sources||[]).map(s=>`<div class="item"><span>${esc(s.source)}</span><span class="badge">${s.chunks} fragments</span></div>`).join(''):'<div class="empty">Aucune connaissance vectorisée.</div>'}</div></div><div class="full"><h3>Ajouter des connaissances</h3><div class="grid"><div><label>Nom de la source</label><input id="brainSource" placeholder="Ex. Manuel chamanisme — Module 1"></div><div class="full"><label>Texte à ingérer</label><textarea id="brainText" style="min-height:220px"></textarea></div></div><div class="actions-row"><button class="btn primary" id="brainIngest">🧠 Ajouter au cerveau</button><button class="btn danger" id="brainWipe">Effacer le cerveau de ce personnage</button></div></div></div></div>`;$('brainIngest').onclick=ingestBrain;$('brainWipe').onclick=wipeBrain}
async function ingestBrain(){const text=$('brainText').value.trim(),source=$('brainSource').value.trim()||'source';if(!current||!text)return status('Personnage et texte requis.','err');status('Vectorisation…');try{await api('/api/vectorize/ingest',{method:'POST',body:JSON.stringify({agent:current,source,text})});await refreshRelated();renderBrain();status('Connaissances ajoutées.','ok')}catch(e){status(e.message,'err')}}
async function wipeBrain(){if(!current)return;if(!confirm('ATTENTION : effacer tout le cerveau vectoriel de '+(form.name||current)+' ?'))return;if(!confirm('Dernière confirmation : cette action supprime les fragments vectorisés de ce personnage.'))return;try{await api('/api/vectorize/wipe',{method:'POST',body:JSON.stringify({agent:current})});await refreshRelated();renderBrain();status('Cerveau vectoriel vidé.','ok')}catch(e){status(e.message,'err')}}
function renderPortals(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Portails & outils</h2><div class="grid"><div><label>Portail principal</label><input id="primaryPortal" value="${esc(form.primaryPortal||'')}" placeholder="diane, praticiens, lena…"></div><div><label>Outils autorisés</label><div class="chips">${TOOLS.map(t=>`<label class="chip"><input data-tool="${t}" type="checkbox" ${(form.tools||[]).includes(t)?'checked':''}> ${t}</label>`).join('')}</div></div><div class="full"><label>Portails existants</label><div class="list">${portals.length?portals.map(p=>`<label class="item"><span><input data-portal="${esc(p.id)}" data-title="${esc(p.title||p.id)}" type="checkbox" ${(form.portalAssignments||[]).some(x=>x.id===p.id)?'checked':''}> <strong>${esc(p.title||p.id)}</strong></span><span class="hint">${esc(p.id)}</span></label>`).join(''):'<div class="empty">Aucun projet de portail trouvé.</div>'}</div></div></div></div>`;qsa('[data-portal]').forEach(cb=>cb.onchange=()=>{const id=cb.dataset.portal;form.portalAssignments=form.portalAssignments||[];const i=form.portalAssignments.findIndex(x=>x.id===id);if(cb.checked&&i<0)form.portalAssignments.push({id,title:cb.dataset.title,role:'specialiste'});if(!cb.checked&&i>=0)form.portalAssignments.splice(i,1)})}
function renderNotes(){const h=$('panel');h.innerHTML=`<div class="card"><h2>Notes internes & versions</h2><div class="grid"><div class="full"><label>Notes internes admin</label><textarea id="f-internalNotes">${esc(form.internalNotes||'')}</textarea></div><div class="full"><label>Tags — séparés par virgules</label><input id="tags" value="${esc((form.tags||[]).join(', '))}"></div><div class="full"><h3>Historique des versions</h3><div class="list">${history.length?history.map(x=>`<div class="item"><div class="meta"><strong>Version ${Number(x.version||0)}</strong><span class="hint">${esc(x.updatedAt||'')}</span></div><button class="btn small" data-restore="${esc(x.key)}">Restaurer</button></div>`).join(''):'<div class="empty">Aucune ancienne version.</div>'}</div></div></div></div>`;qsa('[data-restore]').forEach(b=>b.onclick=()=>restoreVersion(b.dataset.restore))}
async function restoreVersion(key){if(!current||!confirm('Restaurer cette version ? La version actuelle sera conservée dans l’historique.'))return;try{const d=await api('/api/superadmin4/personnages/history/restore',{method:'POST',body:JSON.stringify({code:current,key})});form=normalize(d.profile);profiles[current]=form;await refreshRelated();renderAll();status('Version restaurée.','ok')}catch(e){status(e.message,'err')}}
async function saveCharacter(){collect();collectResources();form.code=slug(form.code||form.name||current);if(!form.name||!form.code)return status('Nom et code requis.','err');status('Enregistrement…');try{await api('/api/personnages/save',{method:'POST',body:JSON.stringify({nom:form.name,code:form.code,portail:form.primaryPortal||''})});const d=await api('/api/superadmin4/personnages/profile',{method:'POST',body:JSON.stringify({...form,sub:form.visibleRole,prompt:form.mission,greeting:form.welcomeMessage,portail:form.primaryPortal})});current=form.code;form=normalize(d.profile);profiles[current]=form;await loadAll();await refreshRelated();renderAll();status('Personnage enregistré dans la KV centrale.','ok')}catch(e){status(e.message,'err')}}
function bind(){if($('saveBtn'))$('saveBtn').onclick=saveCharacter;if($('newBtn'))$('newBtn').onclick=newCharacter;if($('characterSelect'))$('characterSelect').onchange=e=>e.target.value?openCharacter(e.target.value):newCharacter();if($('search'))$('search').oninput=renderCharacterList}
document.addEventListener('DOMContentLoaded',async()=>{if(!(await auth()))return;form=blank();bind();await loadAll();renderAll()});
})();